<?php
namespace MailPoetVendor;
if (!defined('ABSPATH')) exit;
// autoload.php @generated by Composer
require_once __DIR__ . '/composer/autoload_real.php';
return ComposerAutoloaderInit3d2b21591483509f9d473932825fd8a6::getLoader();
