<?php
// THIS FILE IS AUTOGENERATED, PLEASE DON'T EDIT IT DIRECTLY

return array(
	'Search Form' => array(
		__( 'Search Form', 'yith-booking-for-woocommerce' ),
	),
	'Type to search...' => array(
		__( 'Type to search...', 'yith-booking-for-woocommerce' ),
	),
	'No results for "%s".' => array(
		__( 'No results for "%s".', 'yith-booking-for-woocommerce' ),
	),
	'Searching...' => array(
		__( 'Searching...', 'yith-booking-for-woocommerce' ),
	),
	'Show rating' => array(
		__( 'Show rating', 'yith-booking-for-woocommerce' ),
	),
	'Use full-width button' => array(
		__( 'Use full-width button', 'yith-booking-for-woocommerce' ),
	),
	'Use compact view on mobile' => array(
		__( 'Use compact view on mobile', 'yith-booking-for-woocommerce' ),
	),
	'This block will render the current product\'s booking form, so you should use it on single product pages or in a template rendered on the single product pages.' => array(
		__( 'This block will render the current product\'s booking form, so you should use it on single product pages or in a template rendered on the single product pages.', 'yith-booking-for-woocommerce' ),
	),
	'If you are using it on a page/post and you want to show a specific product\'s booking form, please consider using the "Booking form" block instead.' => array(
		__( 'If you are using it on a page/post and you want to show a specific product\'s booking form, please consider using the "Booking form" block instead.', 'yith-booking-for-woocommerce' ),
	),
	'Show title' => array(
		__( 'Show title', 'yith-booking-for-woocommerce' ),
	),
	'Enable to show the product title.' => array(
		__( 'Enable to show the product title.', 'yith-booking-for-woocommerce' ),
	),
	'Title heading tag' => array(
		__( 'Title heading tag', 'yith-booking-for-woocommerce' ),
	),
	'Choose the HTML tag to use for the product title.' => array(
		__( 'Choose the HTML tag to use for the product title.', 'yith-booking-for-woocommerce' ),
	),
	'Enable to show the product rating.' => array(
		__( 'Enable to show the product rating.', 'yith-booking-for-woocommerce' ),
	),
	'Show meta' => array(
		__( 'Show meta', 'yith-booking-for-woocommerce' ),
	),
	'Enable to show the meta section, containing SKU, categories and tags.' => array(
		__( 'Enable to show the meta section, containing SKU, categories and tags.', 'yith-booking-for-woocommerce' ),
	),
	'Edit selected search form' => array(
		__( 'Edit selected search form', 'yith-booking-for-woocommerce' ),
	),
	'Select the search form' => array(
		__( 'Select the search form', 'yith-booking-for-woocommerce' ),
	),
	'Select the search form you want to display' => array(
		__( 'Select the search form you want to display', 'yith-booking-for-woocommerce' ),
	),
	'Done' => array(
		__( 'Done', 'yith-booking-for-woocommerce' ),
	),
	'Text color' => array(
		__( 'Text color', 'yith-booking-for-woocommerce' ),
	),
	'Background color' => array(
		__( 'Background color', 'yith-booking-for-woocommerce' ),
	),
	'Padding' => array(
		__( 'Padding', 'yith-booking-for-woocommerce' ),
	),
	'Border' => array(
		__( 'Border', 'yith-booking-for-woocommerce' ),
	),
	'Border radius' => array(
		__( 'Border radius', 'yith-booking-for-woocommerce' ),
	),
	'Clear all' => array(
		__( 'Clear all', 'yith-booking-for-woocommerce' ),
	),
	'No categories found.' => array(
		__( 'No categories found.', 'yith-booking-for-woocommerce' ),
	),
	'No results for %s' => array(
		__( 'No results for %s', 'yith-booking-for-woocommerce' ),
	),
	'Search categories...' => array(
		__( 'Search categories...', 'yith-booking-for-woocommerce' ),
	),
	'%d category selected' => array(
		_n( '%d category selected', '%d categories selected', 1, 'yith-booking-for-woocommerce' ),
		_n( '%d category selected', '%d categories selected', 2, 'yith-booking-for-woocommerce' ),
	),
	'No products found.' => array(
		__( 'No products found.', 'yith-booking-for-woocommerce' ),
	),
	'Search products...' => array(
		__( 'Search products...', 'yith-booking-for-woocommerce' ),
	),
	'%d product selected' => array(
		_n( '%d product selected', '%d products selected', 1, 'yith-booking-for-woocommerce' ),
		_n( '%d product selected', '%d products selected', 2, 'yith-booking-for-woocommerce' ),
	),
	'No items found.' => array(
		__( 'No items found.', 'yith-booking-for-woocommerce' ),
	),
	'Search for items' => array(
		__( 'Search for items', 'yith-booking-for-woocommerce' ),
	),
	'%d item selected' => array(
		_n( '%d item selected', '%d items selected', 1, 'yith-booking-for-woocommerce' ),
		_n( '%d item selected', '%d items selected', 2, 'yith-booking-for-woocommerce' ),
	),
	'Loading...' => array(
		__( 'Loading...', 'yith-booking-for-woocommerce' ),
	),
	'Blocks - titleLayout' => array(
		_x( 'Layout', 'Blocks - title', 'yith-booking-for-woocommerce' ),
	),
	'Blocks - titleProduct' => array(
		_x( 'Product', 'Blocks - title', 'yith-booking-for-woocommerce' ),
	),
	'Blocks - titleElements' => array(
		_x( 'Elements', 'Blocks - title', 'yith-booking-for-woocommerce' ),
	),
	'Blocks - titleStyle' => array(
		_x( 'Style', 'Blocks - title', 'yith-booking-for-woocommerce' ),
	),
	'Block nameBookable product form' => array(
		_x( 'Bookable product form', 'Block name', 'yith-booking-for-woocommerce' ),
	),
	'Block nameBooking Form' => array(
		_x( 'Booking Form', 'Block name', 'yith-booking-for-woocommerce' ),
	),
	'Block nameBooking form' => array(
		_x( 'Booking form', 'Block name', 'yith-booking-for-woocommerce' ),
	),
	'Block nameBookable Products' => array(
		_x( 'Bookable Products', 'Block name', 'yith-booking-for-woocommerce' ),
	),
	'Block nameBooking Search Form' => array(
		_x( 'Booking Search Form', 'Block name', 'yith-booking-for-woocommerce' ),
	),
	'Bookable Products blockType' => array(
		_x( 'Type', 'Bookable Products block', 'yith-booking-for-woocommerce' ),
	),
	'Bookable Products blockColumns' => array(
		_x( 'Columns', 'Bookable Products block', 'yith-booking-for-woocommerce' ),
	),
	'Bookable Products blockRows' => array(
		_x( 'Rows', 'Bookable Products block', 'yith-booking-for-woocommerce' ),
	),
	'Bookable Products block typesNewest' => array(
		_x( 'Newest', 'Bookable Products block types', 'yith-booking-for-woocommerce' ),
	),
	'Bookable Products block typesHand-picked products' => array(
		_x( 'Hand-picked products', 'Bookable Products block types', 'yith-booking-for-woocommerce' ),
	),
	'Bookable Products block typesProduct categories' => array(
		_x( 'Product categories', 'Bookable Products block types', 'yith-booking-for-woocommerce' ),
	),
	'Bookable Products block typesTop rated' => array(
		_x( 'Top rated', 'Bookable Products block types', 'yith-booking-for-woocommerce' ),
	),
	'Bookable Products block panel titleProducts' => array(
		_x( 'Products', 'Bookable Products block panel title', 'yith-booking-for-woocommerce' ),
	),
	'Bookable Products block panel titleCategories' => array(
		_x( 'Categories', 'Bookable Products block panel title', 'yith-booking-for-woocommerce' ),
	),
	'Bookable Products block panel titleLayout' => array(
		_x( 'Layout', 'Bookable Products block panel title', 'yith-booking-for-woocommerce' ),
	),
	'Block descriptionRender a search form to allow customers to search for bookable products.' => array(
		_x( 'Render a search form to allow customers to search for bookable products.', 'Block description', 'yith-booking-for-woocommerce' ),
	),
	'Border styleSolid' => array(
		_x( 'Solid', 'Border style', 'yith-booking-for-woocommerce' ),
	),
	'Border styleDashed' => array(
		_x( 'Dashed', 'Border style', 'yith-booking-for-woocommerce' ),
	),
	'Border styleDotted' => array(
		_x( 'Dotted', 'Border style', 'yith-booking-for-woocommerce' ),
	),
);