<?php
$seedprod_basic_lpage = '
{
    "no_conflict_mode": false,
    "no_index": false,
    "seo_title": "",
    "seo_description": "",
    "favicon": "",
    "social_thumbnail": "",
    "enable_recaptcha": false,
    "template_id":"",
    "post_title":"",
    "post_name":"",
    "post_status":"",
    "show_powered_by_link":false,
    "affiliate_url":"",
    "header_scripts":"",
    "body_scripts":"",
    "footer_scripts":"",
    "conversion_scripts":"",
    "disable_default_excluded_urls": false,
    "include_exclude_type": "0",
    "include_list": "",
    "exclude_list": "",
    "bypass_phrase": "",
    "bypass_expires": "2",
    "bypass_cookie": false,
    "access_by_ip":"",
    "access_by_role":[],
    "redirect_mode":false,
    "redirect_url":"",
    "domain_mapping_status":false,
    "domain_mapping":"",
    "domain_mapping_force_https":false,
    "exclude_list_404":"",
    "email_integration_id":"",
    "document":{
        "sections":[],
        "settings":{
           "bgStyle": "s",
           "bgGradient":{ "type": "linear","position": "center", "angle": 0,"color1":"","color1location":0,"color2":"","color2location":100 },
           "bgColor":"#FFFFFF",
           "bgImage":"",
           "bgDimming":0,
           "bgOverlayColor":"",
           "bgPosition":"cover",
           "buttonColor":"#000000",
           "headerColor":"#000000",
           "linkColor":"#FF0000",
           "linkDarkerColor":"#cc0000",
           "textColor":"#272727",
           "textFont":"\'Helvetica Neue\', Arial, sans-serif",
           "textFontVariant":"400",
           "headerFont":"\'Helvetica Neue\', Arial, sans-serif",
           "headerFontVariant":"400",
           "contentPosition":"1",
           "customCss":"",
           "headCss":"",
           "mobileCss":"",
           "placeholderCss":"",
           "useVideoBg":false,
           "useVideoBgUrl":"",
           "useSlideshowBg": false,
           "useSlideshowImgs": [""]

        }
     }
 }
 ';

 $seedprod_pro_block_templates = '
 {
  "document":{
      "bgStyle": "s",
      "bgGradient":{ "type": "linear","position": "center", "angle": 0,"color1":"","color1location":0,"color2":"","color2location":100 },
      "bgColor":"#FFFFFF",
      "bgImage":"",
      "bgDimming":0,
      "bgOverlayColor":"",
      "bgPosition":"cover",
      "buttonColor":"#000000",
      "headerColor":"#000000",
      "linkColor":"#FF0000",
      "linkDarkerColor":"#cc0000",
      "textColor":"#272727",
      "textFont":"\'Helvetica Neue\', Arial, sans-serif",
      "textFontVariant":"400",
      "headerFont":"\'Helvetica Neue\', Arial, sans-serif",
      "headerFontVariant":"400",
      "contentPosition":"1",
      "customCss":"",
      "headCss":"",
      "mobileCss":"",
      "placeholderCss":"",
      "useVideoBg":false,
      "useVideoBgUrl":"",
      "useSlideshowBg": false,
      "useSlideshowImgs": [""]
   },
   "row":{
      "bgStyle": "s",
      "bgGradient":{ "type": "linear","position": "center", "angle": 0,"color1":"","color1location":0,"color2":"","color2location":100 },
      "colGutter": 0,
      "width":"1000",
      "bgColor":"",
      "bgImage":"",
      "bgPosition":"",
      "marginTop": "",
      "shadow":"",
      "paddingTop": "0",
      "paddingBottom": "0",
      "paddingLeft": "0",
      "paddingRight": "0",
      "paddingSync": true,
      "borderRadiusTL": "",
      "borderRadiusTR": "",
      "borderRadiusBL": "",
      "borderRadiusBR": "",
      "borderRadiusSync":true,
      "borderTop": "0",
      "borderBottom": "0",
      "borderLeft": "0",
      "borderRight": "0",
      "borderSync": true,
      "borderStyle":"solid"
   },
   "section":{
      "bgStyle": "s",
      "bgGradient":{ "type": "linear","position": "center", "angle": 0,"color1":"","color1location":0,"color2":"","color2location":100 },
      "contentWidth":1,
      "width":"1000",
      "bgColor":"",
      "bgImage":"",
      "bgPosition":"",
      "marginTop": "",
      "shadow":"",
      "paddingTop": "10",
      "paddingBottom": "10",
      "paddingLeft": "10",
      "paddingRight": "10",
      "paddingSync": true,
      "borderRadiusTL": "",
      "borderRadiusTR": "",
      "borderRadiusBL": "",
      "borderRadiusBR": "",
      "borderRadiusSync":true,
      "borderTop": "0",
      "borderBottom": "0",
      "borderLeft": "0",
      "borderRight": "0",
      "borderSync": true,
      "borderStyle":"solid"
   },
   "col":{
    "bgStyle": "s",
    "bgGradient":{ "type": "linear","position": "center", "angle": 0,"color1":"","color1location":0,"color2":"","color2location":100 },
    "colWidth":"",
    "bgColor":"",
    "bgImage":"",
    "bgPosition":"",
    "marginTop": "",
    "shadow":"",
    "paddingTop": "",
    "paddingBottom": "",
    "paddingLeft": "",
    "paddingRight": "",
    "paddingSync": true,
    "borderRadiusTL": "",
    "borderRadiusTR": "",
    "borderRadiusBL": "",
    "borderRadiusBR": "",
    "borderRadiusSync":true,
    "borderTop": "0",
    "borderBottom": "0",
    "borderLeft": "0",
    "borderRight": "0",
    "borderSync": true,
    "borderStyle":"solid"
 },
   "icon":{
     "icon":"fas fa-angle-double-down",
     "color":"",
     "fontSize":"48",
     "align":"center",
     "textShadow":"",
     "marginTop": "0",
     "paddingTop": "",
     "paddingBottom": "",
     "paddingLeft": "",
     "paddingRight": "",
     "paddingSync": true
   },
   "starrating":{
    "label":"",
    "scale":"5",
    "rating":"5",
    "iconSize":"24",
    "spaceBetween":"",
    "align":"center",
    "color":"#fdd835",
    "textColor":"",
    "font": "",
    "fontVariant": "",
    "fontSize": "",
    "fontSize_mobile": "",
    "lineHeight": "",
    "lineHeight_mobile": "",
    "letterSpacing": "",
    "letterSpacing_mobile": "",
    "typographyBold": "",
    "typographyItalic": "",
    "typographyUnderline": "",
    "typographyLetterCase": "",
    "textShadow":"",
    "marginTop": "0",
    "paddingTop": "",
    "paddingBottom": "",
    "paddingLeft": "",
    "paddingRight": "",
    "paddingSync": true
  },
   "feature":{
    "tag": "h2",
    "icon":"",
    "iconColor":"",
    "iconFontSize":"38",
    "headerTxt": "'.__('My Feature or Benefit', 'seedprod-pro').'",
    "layout": "image",
    "txt": "Description",
    "width": "",
    "height": "",
    "align": "left",
    "altTxt": "",
    "src": "",
    "unit":"px",
    "marginTop": "0",
    "paddingTop": "",
    "paddingBottom": "",
    "paddingLeft": "",
    "paddingRight": "",
    "paddingSync": true,
    "font": "",
    "fontVariant": "",
    "fontSize": "",
    "fontSize_mobile": "",
    "lineHeight": "",
    "lineHeight_mobile": "",
    "letterSpacing": "",
    "letterSpacing_mobile": "",
    "typographyBold": "",
    "typographyItalic": "",
    "typographyUnderline": "",
    "typographyLetterCase": "",
    "headerfont": "",
    "headerfontVariant": "",
    "headerfontSize": "",
    "headerfontSize_mobile": "",
    "headerlineHeight": "",
    "headerlineHeight_mobile": "",
    "headerletterSpacing": "",
    "headerletterSpacing_mobile": "",
    "headertypographyBold": "",
    "headertypographyItalic": "",
    "headertypographyUnderline": "",
    "headertypographyLetterCase": ""
   },
   "iconfeature":{
    "tag": "h2",
    "icon":"fas fa-check",
    "iconColor":"",
    "iconFontSize":"38",
    "headerTxt": "'.__('My Feature or Benefit', 'seedprod-pro').'",
    "layout": "icon",
    "txt": "Description",
    "width": "200",
    "height": "",
    "align": "left",
    "altTxt": "",
    "src": "",
    "unit":"px",
    "marginTop": "0",
    "paddingTop": "",
    "paddingBottom": "",
    "paddingLeft": "",
    "paddingRight": "",
    "paddingSync": true,
    "font": "",
    "fontVariant": "",
    "fontSize": "",
    "fontSize_mobile": "",
    "lineHeight": "",
    "lineHeight_mobile": "",
    "letterSpacing": "",
    "letterSpacing_mobile": "",
    "typographyBold": "",
    "typographyItalic": "",
    "typographyUnderline": "",
    "typographyLetterCase": "",
    "headerfont": "",
    "headerfontVariant": "",
    "headerfontSize": "",
    "headerfontSize_mobile": "",
    "headerlineHeight": "",
    "headerlineHeight_mobile": "",
    "headerletterSpacing": "",
    "headerletterSpacing_mobile": "",
    "headertypographyBold": "",
    "headertypographyItalic": "",
    "headertypographyUnderline": "",
    "headertypographyLetterCase": ""
   },
   "header":{
      "headerTxt": "'.__('My Awesome Headline', 'seedprod-pro').'",
      "tag": "h1",
      "textColor": "",
      "bgColor": "",
      "beforeIcon": "",
      "afterIcon": "",
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true,
      "borderRadius": "",
      "border": "",
      "borderStyle": "",
      "borderSize": "",
      "borderColor": "",
      "shadow": "",
      "textShadow": "",
      "font": "",
      "fontVariant": "",
      "fontSize": "",
      "fontSize_mobile": "",
      "lineHeight": "",
      "lineHeight_mobile": "",
      "letterSpacing": "",
      "letterSpacing_mobile": "",
      "typographyBold": "",
      "typographyItalic": "",
      "typographyUnderline": "",
      "align": "center",
      "typographyLetterCase": ""
    },
    "button":{
      "action": "link",
      "link": "",
      "openNewWindow": false,
      "noFollow": false,
      "btnTxt": "Call To Action",
      "btnStyle": "",
      "btnSubTxt": "",
      "btnSubTextSize": "",
      "textColor": "#ffffff",
      "bgColor": "",
      "btnPaddingTop": "16",
      "btnPaddingLeft": "20",
      "btnSize":"4",
      "beforeIcon": "",
      "afterIcon": "",
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true,
      "borderRadius": "4",
      "border": "",
      "borderStyle": "",
      "borderSize": "",
      "borderColor": "",
      "shadow": "",
      "textShadow": "",
      "font": "",
      "fontVariant": "",
      "fontSize": "22",
      "fontSize_mobile": "",
      "lineHeight": "",
      "lineHeight_mobile": "",
      "letterSpacing": "",
      "letterSpacing_mobile": "",
      "typographyBold": "",
      "typographyItalic": "",
      "typographyUnderline": "",
      "align": "center",
      "typographyLetterCase": ""
    },
    "text":{
      "txt": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam commodo velit ex, non ultrices leo auctor at. Integer blandit ex velit, vel aliquam sem tempor eu. Pellentesque sem tortor, elementum et nisi sed, convallis pharetra lorem. Aenean rhoncus rhoncus ex, in dictum massa dictum et. Morbi at nisl fermentum, condimentum tortor a, laoreet leo. Curabitur laoreet diam a metus tincidunt, sed dapibus orci venenatis.",
      "textColor": "",
      "bgColor": "",
      "beforeIcon": "",
      "afterIcon": "",
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true,
      "borderRadius": "",
      "border": "",
      "borderStyle": "",
      "borderSize": "",
      "borderColor": "",
      "shadow": "",
      "textShadow": "",
      "font": "",
      "fontVariant": "",
      "fontSize": "",
      "fontSize_mobile": "",
      "lineHeight": "",
      "lineHeight_mobile": "",
      "letterSpacing": "",
      "letterSpacing_mobile": "",
      "typographyBold": "",
      "typographyItalic": "",
      "typographyUnderline": "",
      "align": "left",
      "typographyLetterCase": ""
    },
    "contactform":{
      "formId":"",
      "textColor":"",
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true,
      "align": "center",
      "font": "",
      "fontVariant": "",
      "fontSize": "",
      "fontSize_mobile": "",
      "lineHeight": "",
      "lineHeight_mobile": "",
      "letterSpacing": "",
      "letterSpacing_mobile": "",
      "typographyBold": "",
      "typographyItalic": "",
      "typographyUnderline": "",
      "align": "left",
      "typographyLetterCase": ""
    },
    "giveaway":{
      "giveawayId":"",
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true,
      "align": "center"
    },
    "image":{
      "link": "",
      "openNewWindow": false,
      "noFollow": false,
      "unit":"px",
      "src": "",
      "altTxt": "",
      "link": "",
      "width": "",
      "height": "",
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true,
      "imagePadding": "",
      "align": "center",
      "shadow": "",
      "imageBorderRadius": "",
      "imageBorderTop": "0",
      "imageBorderBottom": "0",
      "imageBorderLeft": "0",
      "imageBorderRight": "0",
      "imageBorderSync": true,
      "imageBorderStyle":"solid",
      "imageBorderColor": "",
      "blockTemplateId":false
    },
    "divider":{
      "style": "solid",
      "width": "90",
      "height": "1",
      "color": "",
      "align": "center",
      "marginTop": "0",
      "paddingTop": "10",
      "paddingBottom": "10",
      "paddingLeft": "0",
      "paddingRight": "0",
      "paddingSync": false,
      "shadow": ""
    },
    "spacer": {
      "height": 60
    },
    "anchor": {
      "name": ""
    },
    "customhtml":{
      "code": "",
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true
    },
    "shortcode":{
      "shortcode": "",
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true
    },
    "video":{
      "type":"youtube",
      "code": "",
      "youtubeUrl": "https://www.youtube.com/watch?v=MUXoqm3VpRo",
      "width": "100",
      "align": "center",
      "shadow":"",
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true
    },
    "countdown":{
      "countdownType":"",
      "vtHours":"0",
      "vtMinutes":"30",
      "vtSeconds":"0",
      "action":1,
      "thankyouTxt": "",
      "redirectUrl": "",
      "size":"md",
      "timezone": "'.seedprod_pro_get_default_timezone().'",
      "endDate": "",
      "endTime": "",
      "endTimestamp": "",
      "bgColor": "",
      "labelColor": "",
      "dayTxt":"Days",
      "hourTxt":"Hours",
      "minuteTxt":"Minutes",
      "secondTxt":"Seconds",
      "spaceBetween":"20",
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true,
      "borderRadius": "",
      "border": "",
      "borderStyle": "",
      "borderSize": "",
      "borderColor": "",
      "shadow": "",
      "font": "",
      "fontVariant": "",
      "fontSize": "",
      "fontSize_mobile": "",
      "lineHeight": "",
      "lineHeight_mobile": "",
      "letterSpacing": "",
      "letterSpacing_mobile": "",
      "typographyBold": "",
      "typographyItalic": "",
      "typographyUnderline": "",
      "align": "center",
      "typographyLetterCase": "uppercase",
      "blockTemplateId":false
    },
    "bulletlist":{
      "layout": "v",
      "spaceBetween":"10",
      "items": [{ "icon": "fas fa-check", "txt": "Item 1" }],
      "textColor": "",
      "iconColor": "",
      "beforeIcon": "",
      "afterIcon": "",
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true,
      "borderRadius": "",
      "border": "",
      "borderStyle": "",
      "borderSize": "",
      "borderColor": "",
      "shadow": "",
      "textShadow": "",
      "font": "",
      "fontVariant": "",
      "fontSize": "",
      "fontSize_mobile": "",
      "lineHeight": "",
      "lineHeight_mobile": "",
      "letterSpacing": "",
      "letterSpacing_mobile": "",
      "typographyBold": "",
      "typographyItalic": "",
      "typographyUnderline": "",
      "align": "left",
      "typographyLetterCase": "",
      "blockTemplateId":false
    },
    "nav":{
      "layout": "h",
      "spaceBetween":"20",
      "items": [{ "url": "", "txt": "About","openNewWindow":"","noFollow":"" },{ "url": "", "txt": "Contact","openNewWindow":"","noFollow":"" }],
      "textColor": "",
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true,
      "borderRadius": "",
      "border": "",
      "borderStyle": "",
      "borderSize": "",
      "borderColor": "",
      "shadow": "",
      "textShadow": "",
      "font": "",
      "fontVariant": "",
      "fontSize": "",
      "fontSize_mobile": "",
      "lineHeight": "",
      "lineHeight_mobile": "",
      "letterSpacing": "",
      "letterSpacing_mobile": "",
      "typographyBold": "",
      "typographyItalic": "",
      "typographyUnderline": "",
      "align": "left",
      "typographyLetterCase": ""
    },
    "form":{
      "items": []
    },
    "optinform":{
      "align": "center",
      "items": [
        { "type": "email", "label":"'.__('Enter Your Email', 'seedprod-pro').'","txt":"'.__('Email', 'seedprod-pro').'","width":"100","required": true,"display": true},
        { "type": "name", "label":"'.__('Enter Your Name', 'seedprod-pro').'","txt":"'.__('Name', 'seedprod-pro').'","width":"100","required": false, "display": true},
        { "type": "optin_confirm", "label":"'.__('Optin Confirmation', 'seedprod-pro').'","txt":"'.__('Optin Confirmation', 'seedprod-pro').'","width":"100","required": true,"display": false}
      ],
      "action":"1",
      "redirectUrl":"",
      "thankyouTxt":"Thank You, we\'ll be in touch soon.",
      "btnSize":"3",
      "inputSize":"",
      "bgColor":"",
      "btnWidth":"100",
      "btnTxt":"Submit",
      "btnSubTxt":"",
      "btnPaddingTop": "16",
      "btnPaddingLeft": "20",
      "inputPadding": "8",
      "fieldBGColor": "#ffffff",
      "fieldTextColor": "#444444",
      "fieldBorderColor": "#dddddd",
      "fieldborderTop": "1",
      "fieldborderBottom": "1",
      "fieldborderLeft": "1",
      "fieldborderRight": "1",
      "fieldborderSync": true,
      "beforeIcon":"",
      "afterIcon":"",
      "shadow": "",
      "borderRadius": "3",
      "font": "",
      "fontVariant": "",
      "fontSize": "18",
      "fontSize_mobile": "",
      "lineHeight": "",
      "lineHeight_mobile": "",
      "letterSpacing": "",
      "letterSpacing_mobile": "",
      "typographyBold": "",
      "typographyItalic": "",
      "typographyUnderline": "",
      "align": "center",
      "typographyLetterCase": "",
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true,
      "gap": false,
      "blockTemplateId":false
    },
    "progressbar":{
      "txt": "My Text",
      "textShadow": "",
      "shadow": "",
      "width": "60",
      "color": "",
      "outerColor": "#F7F7F7",
      "borderRadius": "3",
      "font": "",
      "fontVariant": "",
      "fontSize": "",
      "fontSize_mobile": "",
      "lineHeight": "",
      "lineHeight_mobile": "",
      "letterSpacing": "",
      "letterSpacing_mobile": "",
      "typographyBold": "",
      "typographyItalic": "",
      "typographyUnderline": "",
      "align": "center",
      "typographyLetterCase": "",
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true,
      "blockTemplateId":false
    },
    "socialprofiles":{
      "iconStyle":"1",
      "iconPadding": 15,
      "iconSize": 24,
      "iconColor": "",
      "size": "md",
      "items": [{ "type": "facebook", "label":"","url":"" },{ "type": "twitter", "label":"","url":"" },{ "type": "instagram", "label":"","url":"" },{ "type": "youtube", "label":"","url":"" }],
      "spaceBetween": "10",
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true,
      "borderRadius": "",
      "border": "",
      "borderStyle": "",
      "borderSize": "",
      "borderColor": "",
      "shadow": "",
      "align": "center",
      "blockTemplateId":false
    },
    "socialsharing":{
      "size": "sm",
      "items": [{ "type": "facebook", "label":"", "meta":"","url":"" },{ "type": "twitter", "label":"", "meta":"","url":"" }],
      "spaceBetween": "20",
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true,
      "borderRadius": "",
      "border": "",
      "borderStyle": "",
      "borderSize": "",
      "borderColor": "",
      "shadow": "",
      "align": "center"
    }


 }
 ';
