<?php
// THIS FILE IS AUTOGENERATED, PLEASE DON'T EDIT IT DIRECTLY

return array(
	"Enabled" => array(
		__( "Enabled", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Open Register" => array(
		__( "Open Register", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Yes" => array(
		__( "Yes", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Note" => array(
		__( "Note", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Customer:" => array(
		__( "Customer:", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Register:" => array(
		__( "Register:", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Name" => array(
		__( "Name", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Address" => array(
		__( "Address", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Phone" => array(
		__( "Phone", 'yith-point-of-sale-for-woocommerce' ),
	),
	"All" => array(
		__( "All", 'yith-point-of-sale-for-woocommerce' ),
	),
	"City" => array(
		__( "City", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Password" => array(
		__( "Password", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Phone:" => array(
		__( "Phone:", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Email:" => array(
		__( "Email:", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Fax:" => array(
		__( "Fax:", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Web:" => array(
		__( "Web:", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Facebook:" => array(
		__( "Facebook:", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Twitter:" => array(
		__( "Twitter:", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Instagram:" => array(
		__( "Instagram:", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Total" => array(
		__( "Total", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Change" => array(
		__( "Change", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Cashier" => array(
		__( "Cashier", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Update" => array(
		__( "Update", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Loading..." => array(
		__( "Loading...", 'yith-point-of-sale-for-woocommerce' ),
	),
	"All Registers" => array(
		__( "All Registers", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Filter by Store" => array(
		__( "Filter by Store", 'yith-point-of-sale-for-woocommerce' ),
	),
	"All Stores" => array(
		__( "All Stores", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Filter by Register" => array(
		__( "Filter by Register", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Orders" => array(
		__( "Orders", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Net Sales" => array(
		__( "Net Sales", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Average Order Value" => array(
		__( "Average Order Value", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Average Items Per Order" => array(
		__( "Average Items Per Order", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Items" => array(
		__( "Items", 'yith-point-of-sale-for-woocommerce' ),
	),
	"New Customers" => array(
		__( "New Customers", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Returning Customers" => array(
		__( "Returning Customers", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Coupons" => array(
		__( "Coupons", 'yith-point-of-sale-for-woocommerce' ),
	),
	"No data for the selected date range" => array(
		__( "No data for the selected date range", 'yith-point-of-sale-for-woocommerce' ),
	),
	"No data recorded for the selected time period." => array(
		__( "No data recorded for the selected time period.", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Payment Method" => array(
		__( "Payment Method", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Amount" => array(
		__( "Amount", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Payment Methods" => array(
		__( "Payment Methods", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Top Cashiers" => array(
		__( "Top Cashiers", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Login times: " => array(
		__( "Login times: ", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Total orders" => array(
		__( "Total orders", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Total sales" => array(
		__( "Total sales", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Download CSV" => array(
		__( "Download CSV", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Register Screen" => array(
		__( "Register Screen", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Order History" => array(
		__( "Order History", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Today's profit" => array(
		__( "Today's profit", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Manage Cash" => array(
		__( "Manage Cash", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Close register" => array(
		__( "Close register", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Store:" => array(
		__( "Store:", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Manage Store" => array(
		__( "Manage Store", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Switch Register" => array(
		__( "Switch Register", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Logout" => array(
		__( "Logout", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Empty Cart" => array(
		__( "Empty Cart", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Add note" => array(
		__( "Add note", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Edit note" => array(
		__( "Edit note", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Add fee or discount" => array(
		__( "Add fee or discount", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Apply coupon" => array(
		__( "Apply coupon", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Shipping" => array(
		__( "Shipping", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Suspend & save cart" => array(
		__( "Suspend & save cart", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Pay" => array(
		__( "Pay", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Add a note to this order" => array(
		__( "Add a note to this order", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Add another payment option" => array(
		__( "Add another payment option", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Amount paying" => array(
		__( "Amount paying", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Amount to pay" => array(
		__( "Amount to pay", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Amount type" => array(
		__( "Amount type", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Back" => array(
		__( "Back", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Balance" => array(
		__( "Balance", 'yith-point-of-sale-for-woocommerce' ),
	),
	"By" => array(
		__( "By", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Cart " => array(
		__( "Cart ", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Change price per unit" => array(
		__( "Change price per unit", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Customer " => array(
		__( "Customer ", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Guest Customer " => array(
		__( "Guest Customer ", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Discount" => array(
		__( "Discount", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Enter coupon code" => array(
		__( "Enter coupon code", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Fee" => array(
		__( "Fee", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Fixed" => array(
		__( "Fixed", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Popular fees" => array(
		__( "Popular fees", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Popular tendered" => array(
		__( "Popular tendered", 'yith-point-of-sale-for-woocommerce' ),
	),
	"load" => array(
		__( "load", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Payment option" => array(
		__( "Payment option", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Pending payment" => array(
		__( "Pending payment", 'yith-point-of-sale-for-woocommerce' ),
	),
	"product" => array(
		__( "product", 'yith-point-of-sale-for-woocommerce' ),
	),
	"products" => array(
		__( "products", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Percentage" => array(
		__( "Percentage", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Reason (optional)" => array(
		__( "Reason (optional)", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Add a reason or note (optional)" => array(
		__( "Add a reason or note (optional)", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Save note" => array(
		__( "Save note", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Shipping Method" => array(
		__( "Shipping Method", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Update Total" => array(
		__( "Update Total", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Save Shipping" => array(
		__( "Save Shipping", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Total due" => array(
		__( "Total due", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Total paying" => array(
		__( "Total paying", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Coupon usage limit has been reached." => array(
		__( "Coupon usage limit has been reached.", 'yith-point-of-sale-for-woocommerce' ),
	),
	"This coupon has expired." => array(
		__( "This coupon has expired.", 'yith-point-of-sale-for-woocommerce' ),
	),
	"The minimum spend for this coupon is %s." => array(
		__( "The minimum spend for this coupon is %s.", 'yith-point-of-sale-for-woocommerce' ),
	),
	"The maximum spend for this coupon is %s." => array(
		__( "The maximum spend for this coupon is %s.", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Sorry, this coupon is not applicable to your cart contents." => array(
		__( "Sorry, this coupon is not applicable to your cart contents.", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Sorry, this coupon is not applicable to selected products." => array(
		__( "Sorry, this coupon is not applicable to selected products.", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Sorry, this coupon is not valid for sale items." => array(
		__( "Sorry, this coupon is not valid for sale items.", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Sorry, this coupon is not applicable to the products: %s." => array(
		__( "Sorry, this coupon is not applicable to the products: %s.", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Sorry, this coupon is not applicable to the categories: %s." => array(
		__( "Sorry, this coupon is not applicable to the categories: %s.", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Sorry, this coupon is not usable by the current customer." => array(
		__( "Sorry, this coupon is not usable by the current customer.", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Guest" => array(
		__( "Guest", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Subtotal" => array(
		__( "Subtotal", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Tax" => array(
		__( "Tax", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Subtotal (incl. tax)" => array(
		__( "Subtotal (incl. tax)", 'yith-point-of-sale-for-woocommerce' ),
	),
	"COUPON" => array(
		__( "COUPON", 'yith-point-of-sale-for-woocommerce' ),
	),
	"You cannot add %s \"%s\" to your cart" => array(
		__( "You cannot add %s \"%s\" to your cart", 'yith-point-of-sale-for-woocommerce' ),
	),
	"You cannot add another \"%s\" to your cart" => array(
		__( "You cannot add another \"%s\" to your cart", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Coupon already applied!" => array(
		__( "Coupon already applied!", 'yith-point-of-sale-for-woocommerce' ),
	),
	"The coupon was not applied!" => array(
		__( "The coupon was not applied!", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Add the first product to the cart" => array(
		__( "Add the first product to the cart", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Are you sure?" => array(
		__( "Are you sure?", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Cancel" => array(
		__( "Cancel", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Coupon not found" => array(
		__( "Coupon not found", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Discount type:" => array(
		__( "Discount type:", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Coupon amount:" => array(
		__( "Coupon amount:", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Expiry date:" => array(
		__( "Expiry date:", 'yith-point-of-sale-for-woocommerce' ),
	),
	"clear" => array(
		__( "clear", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Order #" => array(
		__( "Order #", 'yith-point-of-sale-for-woocommerce' ),
	),
	"items" => array(
		__( "items", 'yith-point-of-sale-for-woocommerce' ),
	),
	"item" => array(
		__( "item", 'yith-point-of-sale-for-woocommerce' ),
	),
	"orders" => array(
		__( "orders", 'yith-point-of-sale-for-woocommerce' ),
	),
	"order" => array(
		__( "order", 'yith-point-of-sale-for-woocommerce' ),
	),
	"All registers" => array(
		__( "All registers", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Note: " => array(
		__( "Note: ", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Other" => array(
		__( "Other", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Total Sales" => array(
		__( "Total Sales", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Youtube:" => array(
		__( "Youtube:", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Order #%s" => array(
		__( "Order #%s", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Paid via %s on %s" => array(
		__( "Paid via %s on %s", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Print Receipt" => array(
		__( "Print Receipt", 'yith-point-of-sale-for-woocommerce' ),
	),
	"< Back to register screen" => array(
		__( "< Back to register screen", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Or create a new customer profile >" => array(
		__( "Or create a new customer profile >", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Create a new customer profile" => array(
		__( "Create a new customer profile", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Company" => array(
		__( "Company", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Country" => array(
		__( "Country", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Current customer" => array(
		__( "Current customer", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Email" => array(
		__( "Email", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Invalid email address" => array(
		__( "Invalid email address", 'yith-point-of-sale-for-woocommerce' ),
	),
	"First name" => array(
		__( "First name", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Last name" => array(
		__( "Last name", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Please enter 3 or more characters" => array(
		__( "Please enter 3 or more characters", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Not found the right customer?" => array(
		__( "Not found the right customer?", 'yith-point-of-sale-for-woocommerce' ),
	),
	"User not found." => array(
		__( "User not found.", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Post Code" => array(
		__( "Post Code", 'yith-point-of-sale-for-woocommerce' ),
	),
	"An account is already registered with this email address." => array(
		__( "An account is already registered with this email address.", 'yith-point-of-sale-for-woocommerce' ),
	),
	"This field is required" => array(
		__( "This field is required", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Save Customer" => array(
		__( "Save Customer", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Save Shipping Address" => array(
		__( "Save Shipping Address", 'yith-point-of-sale-for-woocommerce' ),
	),
	"State" => array(
		__( "State", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Use this customer profile" => array(
		__( "Use this customer profile", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Update customer profile" => array(
		__( "Update customer profile", 'yith-point-of-sale-for-woocommerce' ),
	),
	"VAT / CIF / ID" => array(
		__( "VAT / CIF / ID", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Notice: some information is missing!" => array(
		__( "Notice: some information is missing!", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Billing %s is a required field." => array(
		__( "Billing %s is a required field.", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Billing %s are required fields." => array(
		__( "Billing %s are required fields.", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Shipping %s is a required field." => array(
		__( "Shipping %s is a required field.", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Shipping %s are required fields." => array(
		__( "Shipping %s are required fields.", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Cash in hand" => array(
		__( "Cash in hand", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Reason" => array(
		__( "Reason", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Enter amount" => array(
		__( "Enter amount", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Save Cash" => array(
		__( "Save Cash", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Cash Total" => array(
		__( "Cash Total", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Opening times" => array(
		__( "Opening times", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Closing time" => array(
		__( "Closing time", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Add" => array(
		__( "Add", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Remove" => array(
		__( "Remove", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Add or remove cash" => array(
		__( "Add or remove cash", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Add a note (optional)" => array(
		__( "Add a note (optional)", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Download Report" => array(
		__( "Download Report", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Close Register" => array(
		__( "Close Register", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Product name: " => array(
		__( "Product name: ", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Product category:" => array(
		__( "Product category:", 'yith-point-of-sale-for-woocommerce' ),
	),
	"SKU" => array(
		__( "SKU", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Tax Status:" => array(
		__( "Tax Status:", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Tax Class:" => array(
		__( "Tax Class:", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Regular price:" => array(
		__( "Regular price:", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Stock:" => array(
		__( "Stock:", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Quantity in stock:" => array(
		__( "Quantity in stock:", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Sync with WooCommerce:" => array(
		__( "Sync with WooCommerce:", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Disabled" => array(
		__( "Disabled", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Create product" => array(
		__( "Create product", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Taxable" => array(
		__( "Taxable", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Shipping only" => array(
		__( "Shipping only", 'yith-point-of-sale-for-woocommerce' ),
	),
	"None" => array(
		__( "None", 'yith-point-of-sale-for-woocommerce' ),
	),
	"No results found." => array(
		__( "No results found.", 'yith-point-of-sale-for-woocommerce' ),
	),
	"add to cart" => array(
		__( "add to cart", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Inclusive" => array(
		__( "Inclusive", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Exclusive" => array(
		__( "Exclusive", 'yith-point-of-sale-for-woocommerce' ),
	),
	"No Category found." => array(
		__( "No Category found.", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Invalid or duplicated SKU." => array(
		__( "Invalid or duplicated SKU.", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Standard" => array(
		__( "Standard", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Search a category" => array(
		__( "Search a category", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Please enter a number. If decimal, use the decimal separator (%s). Never use thousand separators." => array(
		__( "Please enter a number. If decimal, use the decimal separator (%s). Never use thousand separators.", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Please enter a positive number. If decimal, use the decimal separator (%s). Never use thousand separators." => array(
		__( "Please enter a positive number. If decimal, use the decimal separator (%s). Never use thousand separators.", 'yith-point-of-sale-for-woocommerce' ),
	),
	"On sale" => array(
		__( "On sale", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Featured" => array(
		__( "Featured", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Add product" => array(
		__( "Add product", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Scan product" => array(
		__( "Scan product", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Add cash in hand" => array(
		__( "Add cash in hand", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Choose variation" => array(
		__( "Choose variation", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Variable product without variations" => array(
		__( "Variable product without variations", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Error" => array(
		__( "Error", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Error: %s" => array(
		__( "Error: %s", 'yith-point-of-sale-for-woocommerce' ),
	),
	"OK" => array(
		__( "OK", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Do you want to delete this cart and start from scratch?" => array(
		__( "Do you want to delete this cart and start from scratch?", 'yith-point-of-sale-for-woocommerce' ),
	),
	"No, continue with this cart" => array(
		__( "No, continue with this cart", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Suspend and save cart" => array(
		__( "Suspend and save cart", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Do you want to load the cart number #%s?" => array(
		__( "Do you want to load the cart number #%s?", 'yith-point-of-sale-for-woocommerce' ),
	),
	"You have some items in your cart. Do you want to suspend your current cart and load the cart number#%s?" => array(
		__( "You have some items in your cart. Do you want to suspend your current cart and load the cart number#%s?", 'yith-point-of-sale-for-woocommerce' ),
	),
	"No, keep the cart" => array(
		__( "No, keep the cart", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Do you want to remove the cart number #%s?" => array(
		__( "Do you want to remove the cart number #%s?", 'yith-point-of-sale-for-woocommerce' ),
	),
	"This cart was switched with the cart number" => array(
		__( "This cart was switched with the cart number", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Apply coupon to order total" => array(
		__( "Apply coupon to order total", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Order total" => array(
		__( "Order total", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Add fee or discount to order total" => array(
		__( "Add fee or discount to order total", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Set customer's profile" => array(
		__( "Set customer's profile", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Shipping Address" => array(
		__( "Shipping Address", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Add a new product" => array(
		__( "Add a new product", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Split Payment" => array(
		__( "Split Payment", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Fix your cart and try again" => array(
		__( "Fix your cart and try again", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Error: You are not able to do this." => array(
		__( "Error: You are not able to do this.", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Profit of" => array(
		__( "Profit of", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Are you sure you want to log out?" => array(
		__( "Are you sure you want to log out?", 'yith-point-of-sale-for-woocommerce' ),
	),
	"Title of Close Register modalClose Register" => array(
		_x( "Close Register", "Title of Close Register modal", 'yith-point-of-sale-for-woocommerce' ),
	),
);