DROP TABLE `user_list`;
-- QUERY ---
DROP TABLE `user`;
-- QUERY ---
DROP TABLE `list`;
-- QUERY ---
DROP TABLE `campaign`;
-- QUERY ---
DROP TABLE `campaign_list`;
-- QUERY ---
DROP TABLE `email`;
-- QUERY ---
DROP TABLE `user_field`;
-- QUERY ---
DROP TABLE `queue`;
-- QUERY ---
DROP TABLE `user_history`;
-- QUERY ---
DROP TABLE `email_user_stat`;
-- QUERY ---
DROP TABLE `url`;
-- QUERY ---
DROP TABLE `email_user_url`;
-- QUERY ---
DROP TABLE `url_mail`;
-- QUERY ---
DROP TABLE `form`;
-- QUERY ---
DROP TABLE `custom_field`;
-- QUERY ---
DROP TABLE `subscriber_ips`;
