<?php
define('PAFE_FEATURES', json_encode(array(
            array(
                'name' => 'ACF Repeater Render',
                'option' => 'pafe-features-acf-repeater-render',
                'url' => 'https://pafe.piotnet.com/docs/acf-repeater-render/?wpam_id=1',
                'pro' => 1,
                'widget' => true,
            ), array(
                'name' => 'Absolute Positioning',
                'option' => 'pafe-features-absolute-positioning',
                'url' => 'https://pafe.piotnet.com/?wpam_id=1#absolute-positioning',
                'pro' => 1,
                'extension' => true,
            ), array(
                'name' => 'Address Autocomplete Field',
                'option' => 'pafe-features-address-autocomplete-field',
                'url' => 'https://pafe.piotnet.com/docs/form-builder/?wpam_id=1',
                'pro' => 1,
                'form-builder' => true,
            ), array(
                'name' => 'Advanced Dots Styling',
                'option' => 'pafe-features-advanced-dots-styling',
                'url' => 'https://pafe.piotnet.com/docs/navigation-arrows-icon-and-advanced-dots-styling-for-slides-and-image-carousel-widget/?wpam_id=1',
                'pro' => 1,
                'extension' => true,
            ), array(
                'name' => 'Advanced Form Styling',
                'option' => 'pafe-features-advanced-form-styling',
                'url' => 'https://pafe.piotnet.com/docs/advanced-form-styling/?wpam_id=1',
                'pro' => 1,
                'extension' => true,
            ), array(
                'name' => 'Advanced Nav Menu Styling',
                'option' => 'pafe-features-advanced-nav-menu-styling',
                'url' => 'https://pafe.piotnet.com/docs/advanced-nav-menu-styling-custom-toggle-image-dropdown-absolute/?wpam_id=1',
                'pro' => 1,
                'extension' => true,
            ), array(
                'name' => 'Advanced Search',
                'option' => 'pafe-features-advanced-search',
                'url' => 'https://pafe.piotnet.com/docs/advanced-search/?wpam_id=1',
                'pro' => 1,
                'widget' => true,
            ), array(
                'name' => 'Advanced Tabs Styling',
                'option' => 'pafe-features-advanced-tabs-styling',
                'url' => 'https://pafe.piotnet.com/docs/advanced-tabs-styling/?wpam_id=1',
                'pro' => 1,
                'extension' => true,
            ), array(
                'name' => 'Ajax Live Search',
                'option' => 'pafe-features-ajax-live-search',
                'url' => 'https://pafe.piotnet.com/docs/ajax-live-search/?wpam_id=1',
                'pro' => 1,
                'extension' => true,
            ), array(
                'name' => 'Before After Image Comparison Slider',
                'option' => 'pafe-features-before-after-image-comparison-slider',
                'url' => 'https://pafe.piotnet.com/docs/before-after-image-comparison-slider/?wpam_id=1',
                'pro' => false,
                'widget' => true,
            ), array(
                'name' => 'Calculated Fields Form',
                'option' => 'pafe-features-calculated-fields-form',
                'url' => 'https://pafe.piotnet.com/docs/form-builder/?wpam_id=1',
                'pro' => 1,
                'extension' => true,
            ), array(
                'name' => 'Close First Accordion',
                'option' => 'pafe-features-close-first-accordion',
                'url' => 'https://pafe.piotnet.com/docs/close-first-accordion/?wpam_id=1',
                'pro' => 1,
                'extension' => true,
            ), array(
                'name' => 'Column Aspect Ratio',
                'option' => 'pafe-features-column-aspect-ratio',
                'url' => 'https://pafe.piotnet.com/docs/column-aspect-ratio/?wpam_id=1',
                'pro' => 1,
                'extension' => true,
            ), array(
                'name' => 'Column Link',
                'option' => 'pafe-features-column-link',
                'url' => 'https://pafe.piotnet.com/docs/section-link-column-link/?wpam_id=1',
                'pro' => 1,
                'extension' => true,
            ), array(
                'name' => 'Column Width ( Pixel, %, calc )',
                'option' => 'pafe-features-column-width',
                'url' => 'https://pafe.piotnet.com/docs/column-width-pixel-calc/?wpam_id=1',
                'pro' => 1,
                'extension' => true,
            ), array(
                'name' => 'Conditional Logic Form',
                'option' => 'pafe-features-conditional-logic-form',
                'url' => 'https://pafe.piotnet.com/docs/form-builder/?wpam_id=1',
                'pro' => 1,
                'extension' => true,
            ), array(
                'name' => 'Conditional Visibility',
                'option' => 'pafe-features-conditional-visibility',
                'url' => 'https://pafe.piotnet.com/docs/conditional-visibility/?wpam_id=1',
                'pro' => 1,
                'extension' => true,
            ), array(
                'name' => 'Connect Form to Google Calendar',
                'option' => 'pafe-features-form-google-calendar-connector',
                'url' => 'https://pafe.piotnet.com/docs/form-builder/?wpam_id=1',
                'pro' => 1,
                'form-builder' => true,
            ), array(
                'name' => 'Connect Form to Google Sheets',
                'option' => 'pafe-features-form-google-sheets-connector',
                'url' => 'https://pafe.piotnet.com/docs/google-sheets-connector/?wpam_id=1',
                'pro' => 1,
                'extension' => true,
            ), array(
                'name' => 'Convert Image To Black Or White',
                'option' => 'pafe-features-convert-image-to-black-or-white',
                'url' => 'https://pafe.piotnet.com/docs/convert-image-to-black-or-white/?wpam_id=1',
                'pro' => 1,
                'extension' => true,
            ), array(
                'name' => 'Countdown Cart',
                'option' => 'pafe-features-countdown-cart',
                'url' => 'https://pafe.piotnet.com/docs/countdown-cart/?wpam_id=1',
                'pro' => false,
                'widget' => true,
            ), array(
                'name' => 'Crossfade Multiple Background Images',
                'option' => 'pafe-features-crossfade-multiple-background-images',
                'url' => 'https://pafe.piotnet.com/docs/crossfade-multiple-background-images/?wpam_id=1',
                'pro' => 1,
                'extension' => true,
            ), array(
                'name' => 'Css Filters',
                'option' => 'pafe-features-css-filters',
                'url' => 'https://pafe.piotnet.com/docs/css-filters-for-any-widgets-section-column/?wpam_id=1',
                'pro' => 1,
                'extension' => true,
            ), array(
                'name' => 'Custom Media Query Breakpoints',
                'option' => 'pafe-features-custom-media-query-breakpoints',
                'url' => 'https://pafe.piotnet.com/docs/custom-media-query-breakpoints/?wpam_id=1',
                'pro' => 1,
                'extension' => true,
            ), array(
                'name' => 'Display Form Submissions',
                'option' => 'pafe-features-display-form-submissions',
                'url' => 'https://pafe.piotnet.com/?wpam_id=1#display-form-submissions/?wpam_id=1',
                'pro' => 1,
            ),array(
                'name' => 'Display Inline Block',
                'option' => 'pafe-features-display-inline-block',
                'url' => 'https://pafe.piotnet.com/?wpam_id=1#display-inline-block/?wpam_id=1',
                'pro' => 1,
                'extension' => true,
            ), array(
                'name' => 'Dual Color Headline',
                'option' => 'pafe-features-dual-color-headline',
                'url' => 'https://pafe.piotnet.com/docs/dual-color-headline/?wpam_id=1',
                'pro' => false,
                'widget' => true,
            ), array(
                'name' => 'Equal Height',
                'option' => 'pafe-features-equal-height',
                'url' => 'https://pafe.piotnet.com/docs/equal-height/?wpam_id=1',
                'pro' => 1,
                'extension' => true,
            ), array(
                'name' => 'Equal Height For CTA',
                'option' => 'pafe-features-equal-height-for-cta',
                'url' => 'https://pafe.piotnet.com/docs/equal-height/?wpam_id=1',
                'pro' => 1,
                'extension' => true,
            ), array(
                'name' => 'Equal Height For WooCommerce Products',
                'option' => 'pafe-features-equal-height-for-woocommerce-products',
                'url' => 'https://pafe.piotnet.com/docs/equal-height/?wpam_id=1',
                'pro' => 1,
                'extension' => true,
            ), array(
                'name' => 'Font Awesome 5',
                'option' => 'pafe-features-font-awesome-5',
                'url' => 'https://pafe.piotnet.com/?wpam_id=1#font-awesome-5',
                'pro' => 1,
                'extension' => true,
            ), array(
                'name' => 'Form Abandonment',
                'option' => 'pafe-features-form-abandonment',
                'url' => 'https://pafe.piotnet.com/docs/form-builder/?wpam_id=1',
                'pro' => 1,
                'extension' => true,
            ), array(
                'name' => 'Form Builder',
                'option' => 'pafe-features-form-builder',
                'url' => 'https://pafe.piotnet.com/docs/form-builder/?wpam_id=1',
                'pro' => 1,
                'form-builder' => true,
            ), array(
                'name' => 'Form Style',
                'option' => 'pafe-features-form-style',
                'url' => 'https://pafe.piotnet.com/docs/form-style/?wpam_id=1',
                'pro' => false,
                'extension' => true,
            ), array(
                'name' => 'Gradient Button',
                'option' => 'pafe-features-gradient-button',
                'url' => 'https://pafe.piotnet.com/docs/gradient-text-gradient-button/?wpam_id=1',
                'pro' => false,
                'extension' => true,
            ), array(
                'name' => 'Gradient Text',
                'option' => 'pafe-features-gradient-text',
                'url' => 'https://pafe.piotnet.com/docs/gradient-text-gradient-button/?wpam_id=1',
                'pro' => false,
                'extension' => true,
            ), array(
                'name' => 'Hotspot',
                'option' => 'pafe-features-hotspot',
                'url' => 'https://pafe.piotnet.com/docs/hotspot/?wpam_id=1',
                'pro' => false,
                'widget' => true,
            ), array(
                'name' => 'Hubspot Integration',
                'option' => 'pafe-features-hubspot',
                'url' => 'https://pafe.piotnet.com/docs/form-builder/?wpam_id=1',
                'pro' => 1,
                'form-builder' => true,
            ), array(
                'name' => 'Image Accordion',
                'option' => 'pafe-features-image-accordion',
                'url' => 'https://pafe.piotnet.com/docs/image-accordion/?wpam_id=1',
                'pro' => false,
                'widget' => true,
            ), array(
                'name' => 'Image Carousel Multiple Custom Urls',
                'option' => 'pafe-features-image-carousel-multiple-custom-urls',
                'url' => 'https://pafe.piotnet.com/docs/image-carousel-multiple-custom-urls/?wpam_id=1',
                'pro' => false,
                'extension' => true,
            ), array(
                'name' => 'Image Select Field',
                'option' => 'pafe-features-image-select-field',
                'url' => 'https://pafe.piotnet.com/docs/form-builder/?wpam_id=1',
                'pro' => 1,
                'extension' => true,
            ), array(
                'name' => 'Lightbox Gallery Masonry',
                'option' => 'pafe-features-lightbox-gallery',
                'url' => 'https://pafe.piotnet.com/docs/lightbox-gallery-masonry-with-title-and-caption-thumbnail-custom-size/?wpam_id=1',
                'pro' => 1,
                'widget' => true,
            ), array(
                'name' => 'Lightbox Image',
                'option' => 'pafe-features-lightbox-image',
                'url' => 'https://pafe.piotnet.com/docs/lightbox-gallery-masonry-with-title-and-caption-thumbnail-custom-size/?wpam_id=1',
                'pro' => 1,
                'widget' => true,
            ), array(
                'name' => 'Max Width',
                'option' => 'pafe-features-max-width',
                'url' => 'https://pafe.piotnet.com/?wpam_id=1#max-width',
                'pro' => 1,
                'extension' => true,
            ), array(
                'name' => 'Media Carousel Aspect Ratio',
                'option' => 'pafe-features-media-carousel-ratio',
                'url' => 'https://pafe.piotnet.com/docs/media-carousel-ratio/?wpam_id=1',
                'pro' => 1,
                'extension' => true,
            ), array(
                'name' => 'Multi Step Form',
                'option' => 'pafe-features-multi-step-form',
                'url' => 'https://pafe.piotnet.com/docs/form-builder/?wpam_id=1',
                'pro' => 1,
                'form-builder' => true,
            ), array(
                'name' => 'Multiple Background Images',
                'option' => 'pafe-features-multiple-background-images',
                'url' => 'https://pafe.piotnet.com/docs/multiple-background-images/?wpam_id=1',
                'pro' => 1,
                'extension' => true,
            ), array(
                'name' => 'Navigation Arrows Icon',
                'option' => 'pafe-features-navigation-arrows-icon',
                'url' => 'https://pafe.piotnet.com/docs/navigation-arrows-icon-and-advanced-dots-styling-for-slides-and-image-carousel-widget/?wpam_id=1',
                'pro' => 1,
                'extension' => true,
            ), array(
                'name' => 'PAFE Form Builder Conditional Logic',
                'option' => 'pafe-features-form-builder-conditional-logic',
                'url' => 'https://pafe.piotnet.com/docs/form-builder/?wpam_id=1',
                'pro' => 1,
                'form-builder' => true,
            ), array(
                'name' => 'Parallax Background',
                'option' => 'pafe-features-parallax-background',
                'url' => 'https://pafe.piotnet.com/docs/parallax-background-for-every-element/?wpam_id=1',
                'pro' => 1,
                'extension' => true,
            ), array(
                'name' => 'Particles',
                'option' => 'pafe-features-particles',
                'url' => 'https://pafe.piotnet.com/docs/particles/?wpam_id=1',
                'pro' => false,
                'extension' => true,
            ), array(
                'name' => 'Paypal Payment',
                'option' => 'pafe-features-paypal-payment',
                'url' => 'https://pafe.piotnet.com/docs/form-builder/?wpam_id=1',
                'pro' => 1,
                'form-builder' => true,
            ), array(
                'name' => 'Popup Trigger URL',
                'option' => 'pafe-features-popup-trigger-url',
                'url' => 'https://pafe.piotnet.com/docs/popup-trigger-url/?wpam_id=1',
                'pro' => 1,
                'extension' => true,
            ), array(
                'name' => 'Posts List',
                'option' => 'pafe-features-posts-list',
                'url' => 'https://pafe.piotnet.com/docs/posts-list/?wpam_id=1',
                'pro' => false,
                'widget' => true,
            ), array(
                'name' => 'Progress Bar',
                'option' => 'pafe-features-progressbar',
                'url' => 'https://pafe.piotnet.com/docs/progressbar/?wpam_id=1',
                'pro' => false,
                'widget' => true,
            ),
            array(
                'name' => 'Range Slider Field',
                'option' => 'pafe-features-range-slider',
                'url' => 'https://pafe.piotnet.com/docs/form-builder/?wpam_id=1',
                'pro' => 1,
                'extension' => true,
            ),
            array(
                'name' => 'Responsive Background',
                'option' => 'pafe-features-responsive-background',
                'url' => 'https://pafe.piotnet.com/docs/responsive-background-color/?wpam_id=1',
                'pro' => 1,
                'extension' => true,
            ),
            array(
                'name' => 'Responsive Border Width',
                'option' => 'pafe-features-responsive-border-width',
                'url' => 'https://pafe.piotnet.com/?wpam_id=1#responsive-border-width',
                'pro' => 1,
                'extension' => true,
            ),
            array(
                'name' => 'Responsive Column Order',
                'option' => 'pafe-features-responsive-column-order',
                'url' => 'https://pafe.piotnet.com/docs/responsive-column-order/?wpam_id=1',
                'pro' => 1,
                'extension' => true,
            ),
            array(
                'name' => 'Responsive Custom Positioning',
                'option' => 'pafe-features-responsive-custom-positioning',
                'url' => 'https://pafe.piotnet.com/docs/responsive-custom-positioning/?wpam_id=1',
                'pro' => 1,
                'extension' => true,
            ),
            array(
                'name' => 'Responsive Gallery Column Width',
                'option' => 'pafe-features-responsive-gallery-column-width',
                'url' => 'https://pafe.piotnet.com/docs/lightbox-gallery-masonry-with-title-and-caption-thumbnail-custom-size/?wpam_id=1',
                'pro' => 1,
                'extension' => true,
            ),
            array(
                'name' => 'Responsive Gallery Images Spacing',
                'option' => 'pafe-features-responsive-gallery-images-spacing',
                'url' => 'https://pafe.piotnet.com/docs/lightbox-gallery-masonry-with-title-and-caption-thumbnail-custom-size/?wpam_id=1',
                'pro' => 1,
                'extension' => true,
            ),
            array(
                'name' => 'Responsive Hide Column',
                'option' => 'pafe-features-responsive-hide-column',
                'url' => 'https://pafe.piotnet.com/?wpam_id=1#responsive-hide-column',
                'pro' => 1,
                'extension' => true,
            ),
            array(
                'name' => 'Responsive Section Column Text Align',
                'option' => 'pafe-features-responsive-section-column-text-align',
                'url' => 'https://pafe.piotnet.com/docs/responsive-section-column-text-align/?wpam_id=1',
                'pro' => 1,
                'extension' => true,
            ),
            array(
                'name' => 'Sales Pop',
                'option' => 'pafe-features-sales-pop',
                'url' => 'https://pafe.piotnet.com/docs/sales-pop/?wpam_id=1',
                'pro' => false,
                'widget' => true,
            ),
            array(
                'name' => 'Scroll Box With Custom Scrollbar',
                'option' => 'pafe-features-scroll-box-with-custom-scrollbar',
                'url' => 'https://pafe.piotnet.com/docs/scroll-box-with-custom-scrollbar/?wpam_id=1',
                'pro' => 1,
                'extension' => true,
            ),
            array(
                'name' => 'Section Link',
                'option' => 'pafe-features-section-link',
                'url' => 'https://pafe.piotnet.com/docs/section-link-column-link/?wpam_id=1',
                'pro' => 1,
                'extension' => true,
            ),
            array(
                'name' => 'Select Autocomplete Field',
                'option' => 'pafe-features-select-autocomplete-field',
                'url' => 'https://pafe.piotnet.com/docs/form-builder/?wpam_id=1',
                'pro' => 1,
                'form-builder' => true,
            ),
            array(
                'name' => 'Signature Field',
                'option' => 'pafe-features-signature-field',
                'url' => 'https://pafe.piotnet.com/docs/form-builder/?wpam_id=1',
                'pro' => 1,
                'form-builder' => true,
            ),
            array(
                'name' => 'Slider Builder',
                'option' => 'pafe-features-slider-builder',
                'url' => 'https://pafe.piotnet.com/docs/slider-builder-with-animation/?wpam_id=1',
                'pro' => 1,
                'widget' => true,
            ),
            array(
                'name' => 'Sticky Header',
                'option' => 'pafe-features-sticky-header',
                'url' => 'https://pafe.piotnet.com/docs/sticky-header/?wpam_id=1',
                'pro' => 1,
                'extension' => true,
            ),
            array(
                'name' => 'Stripe Payment',
                'option' => 'pafe-features-stripe-payment',
                'url' => 'https://pafe.piotnet.com/docs/form-builder/?wpam_id=1',
                'pro' => 1,
                'form-builder' => true,
            ),
            array(
                'name' => 'Submit Post',
                'option' => 'pafe-features-submit-post',
                'url' => 'https://pafe.piotnet.com/docs/form-builder/?wpam_id=1',
                'pro' => 1,
                'form-builder' => true,
            ),
            array(
                'name' => 'Switch Content',
                'option' => 'pafe-features-switch-content',
                'url' => 'https://pafe.piotnet.com/docs/switch-content/?wpam_id=1',
                'pro' => false,
                'widget' => true,
            ),
            array(
                'name' => 'Table',
                'option' => 'pafe-features-table',
                'url' => 'https://pafe.piotnet.com/docs/table/?wpam_id=1',
                'pro' => false,
                'widget' => true,
            ),
            array(
                'name' => 'Text Color Change on Column Hover',
                'option' => 'pafe-features-text-color-change-on-column-hover',
                'url' => 'https://pafe.piotnet.com/docs/text-color-change-on-column-hover/?wpam_id=1',
                'pro' => 1,
                'extension' => true,
            ),
            array(
                'name' => 'Toggle Content',
                'option' => 'pafe-features-toggle-content',
                'url' => 'https://pafe.piotnet.com/docs/toggle-content-readmore-content/?wpam_id=1',
                'pro' => 1,
                'extension' => true,
            ),
            array(
                'name' => 'Tooltip',
                'option' => 'pafe-features-tooltip',
                'url' => 'https://pafe.piotnet.com/docs/tooltip/?wpam_id=1',
                'pro' => false,
                'extension' => true,
            ),
            array(
                'name' => 'Vertical Timeline',
                'option' => 'pafe-features-vertical-timeline',
                'url' => 'https://pafe.piotnet.com/docs/vertical-timeline/?wpam_id=1',
                'pro' => false,
                'widget' => true,
            ),
            array(
                'name' => 'Video Playlist',
                'option' => 'pafe-features-video-playlist',
                'url' => 'https://pafe.piotnet.com/docs/video-playlist/?wpam_id=1',
                'pro' => false,
                'widget' => true,
            ),
            array(
                'name' => 'Widget Creator',
                'option' => 'pafe-features-widget-creator',
                'url' => 'https://pafe.piotnet.com/docs/pafe-widget-creator/?wpam_id=1',
                'pro' => 1,
                'widget' => true,
            ),
            array(
                'name' => 'WooCommerce Checkout',
                'option' => 'pafe-features-woocommerce-checkout',
                'url' => 'https://pafe.piotnet.com/docs/woocommerce-one-page-checkout/?wpam_id=1',
                'pro' => 1,
                'form-builder' => true,
                'woocommerce_sales_funnels' => true,
            ),
            array(
                'name' => 'WooCommerce Sales Funnel',
                'option' => 'pafe-features-woocommerce-sales-funnel',
                'url' => 'https://pafe.piotnet.com/docs/woocommerce-sales-funnel/?wpam_id=1',
                'pro' => 1,
                'form-builder' => true,
                'woocommerce_sales_funnels' => true,
            ),
        )
    )
);
?>
