<?php
/**
 * Badge Metabox
 *
 * @author   YITH <plugins@yithemes.com>
 * @package  YITH\BadgeManagementPremium\PluginOptions
 * @since    2.0
 */

$remote_badge_list = yith_wcbm_get_remote_badges_list();

return array(
	'label'    => __( 'Badge Options', 'yith-woocommerce-badges-management' ),
	'pages'    => YITH_WCBM_Post_Types::$badge,
	'priority' => 'high',
	'class'    => yith_set_wrapper_class() . ' yith-wcbm-badge-options-metabox',
	'tabs'     => array(
		'badge-options' => array(
			'label'  => __( 'Text Badge', 'yith-woocommerce-badges-management' ),
			'fields' => array(
				'yith_wcbm_badge_security' => array(
					'type' => 'hidden',
					'std'  => wp_create_nonce( 'yith_wcbm_save_badge' ),
					'name' => 'yith_wcbm_badge_security',
				),
				'post-title'               => array(
					'label'             => __( 'Badge name', 'yith-woocommerce-badges-management' ),
					'type'              => 'text',
					'name'              => 'post_title',
					'id'                => 'yith-wcbm-title',
					'custom_attributes' => array(
						'placeholder' => __( 'Badge name', 'yith-woocommerce-badges-management' ),
						'required'    => 'true',
					),
					'desc'              => __( 'Enter a name to identify this badge', 'yith-woocommerce-badges-management' ),
				),
				'type'                     => array(
					'name'            => 'yith_wcbm_badge[_type]',
					'label'           => __( 'Badge type', 'yith-woocommerce-badges-management' ),
					'type'            => 'select',
					'class'           => 'yith-wcbm-badge-type yith-enhanced-select',
					'extra_row_class' => 'yith-wcbm-badge-type-row',
					'options'         => array(
						'text'     => __( 'Text', 'yith-woocommerce-badges-management' ),
						'image'    => __( 'Image', 'yith-woocommerce-badges-management' ),
						'css'      => __( 'CSS', 'yith-woocommerce-badges-management' ),
						'advanced' => __( 'Advanced', 'yith-woocommerce-badges-management' ),
					),
					'std'             => isset( $_GET['badge-type'], $_GET['security'] ) && wp_verify_nonce( sanitize_text_field( wp_unslash( $_GET['security'] ) ), 'yith_wcbm_create_badge' ) && in_array( $_GET['badge-type'], array( 'text', 'image', 'css', 'advanced' ), true ) ? sanitize_text_field( wp_unslash( $_GET['badge-type'] ) ) : 'text',
					'desc'            => __( 'Choose the badge type', 'yith-woocommerce-badges-management' ),
				),
				'image'                    => array(
					'name'              => 'yith_wcbm_badge[_image]',
					// translators: %1$s is an opening HTML Container, %2$s is the closing HTML Container.
					'custom_label'      => sprintf( esc_html__( 'Choose the badge image or upload a custom one', 'yith-woocommerce-badges-management' ), '<span class="yith-wcbm-select">', '</span>' ),
					'type'              => 'custom',
					'extra_row_class'   => 'yith-wcbm-badge-image-row yith-wcbm-visible-if-image',
					'action'            => 'yith_wcbm_print_badge_library_field',
					'allow_upload'      => 'yes',
					'library'           => yith_wcbm_get_badges_list( 'image' ),
					'importable_badges' => $remote_badge_list['image'],
					'url'               => YITH_WCBM_ASSETS_URL . 'images/image-badges/',
					'std'               => '1.svg',
				),
				'css'                      => array(
					'name'              => 'yith_wcbm_badge[_css]',
					'custom_label'      => __( 'Choose the badge image', 'yith-woocommerce-badges-management' ),
					'type'              => 'custom',
					'extra_row_class'   => 'yith-wcbm-badge-css-row yith-wcbm-visible-if-css',
					'action'            => 'yith_wcbm_print_badge_library_field',
					'allow_upload'      => 'no',
					'library'           => yith_wcbm_get_badges_list( 'css' ),
					'importable_badges' => $remote_badge_list['css'],
					'url'               => YITH_WCBM_ASSETS_URL . 'images/css-badge-previews/',
					'std'               => '1.svg',
				),
				'advanced'                 => array(
					'name'              => 'yith_wcbm_badge[_advanced]',
					'custom_label'      => __( 'Choose the badge image', 'yith-woocommerce-badges-management' ),
					'type'              => 'custom',
					'extra_row_class'   => 'yith-wcbm-badge-advanced-row yith-wcbm-visible-if-advanced',
					'action'            => 'yith_wcbm_print_badge_library_field',
					'allow_upload'      => 'no',
					'library'           => yith_wcbm_get_badges_list( 'advanced' ),
					'importable_badges' => $remote_badge_list['advanced'],
					'url'               => YITH_WCBM_ASSETS_URL . 'images/advanced-badge-previews/',
					'std'               => '1.svg',
				),
				'advanced_display'         => array(
					'name'    => 'yith_wcbm_badge[_advanced_display]',
					'label'   => __( 'Display', 'yith-woocommerce-badges-management' ),
					'desc'    => __( 'Choose if you want to display the amount of the discount on a product or the discount percentage.', 'yith-woocommerce-badges-management' ),
					'type'    => 'radio',
					'class'   => 'yith-wcbm-radio-pill-style',
					'options' => array(
						'amount'     => __( 'Amount', 'yith-woocommerce-badges-management' ),
						'percentage' => __( 'Percentage', 'yith-woocommerce-badges-management' ),
					),
					'std'     => 'percentage',
				),
				'text'                     => array(
					'name'            => 'yith_wcbm_badge[_text]',
					'label'           => __( 'Text', 'yith-woocommerce-badges-management' ),
					// 'desc'            => __( 'Use the editor to add the badge text.', 'yith-woocommerce-badges-management' ),
					// TODO: update the description once the modal is developed.
					'desc'            => __( 'Use the editor to add the badge text.<br>Need to show dynamic content? <span class="yith-wcbm-check-for-placeholders">Check the placeholders availables!</span>', 'yith-woocommerce-badges-management' ),
					'type'            => 'textarea',
					'extra_row_class' => 'yith-wcbm-text-editor-row yith-wcbm-visible-if-text yith-wcbm-visible-if-css',
					'class'           => 'yith-wcbm-text-editor',
					'std'             => 'Text',
				),
				'background_color'         => array(
					'name'            => 'yith_wcbm_badge[_background_color]',
					'label'           => __( 'Background color', 'yith-woocommerce-badges-management' ),
					'type'            => 'colorpicker',
					'extra_row_class' => 'yith-wcbm-visible-if-text yith-wcbm-visible-if-css yith-wcbm-visible-if-advanced',
					'alpha_enabled'   => false,
					'class'           => 'yith-plugin-fw-colorpicker yith-wcbm-background-colorpicker',
					'std'             => '#2470FF',
					'desc'            => __( 'Set the badge background color.', 'yith-woocommerce-badges-management' ),
				),
				'text_color'               => array(
					'name'            => 'yith_wcbm_badge[_text_color]',
					'label'           => __( 'Text color', 'yith-woocommerce-badges-management' ),
					'type'            => 'colorpicker',
					'extra_row_class' => 'yith-wcbm-visible-if-advanced',
					'alpha_enabled'   => false,
					'class'           => 'yith-plugin-fw-colorpicker yith-wcbm-text-colorpicker',
					'std'             => '#FFFFFF',
					'desc'            => __( 'Set the badge text color.', 'yith-woocommerce-badges-management' ),
				),
				'size'                     => array(
					'name'            => 'yith_wcbm_badge[_size]',
					'label'           => __( 'Size (px)', 'yith-woocommerce-badges-management' ),
					'type'            => 'dimensions',
					'extra_row_class' => 'yith-wcbm-visible-if-text',
					'dimensions'      => array(
						'width'  => __( 'Width', 'yith-woocommerce-badges-management' ),
						'height' => __( 'Height', 'yith-woocommerce-badges-management' ),
					),
					'units'           => array(
						'px' => 'px',
					),
					'min'             => 0,
					'std'             => array(
						'dimensions' => array(
							'width'  => 100,
							'height' => 50,
						),
						'linked'     => 'no',
						'unit'       => 'px',
					),
					'desc'            => __( 'Set the badge size.', 'yith-woocommerce-badges-management' ),
				),
				'uploaded_image_width'     => array(
					'name'            => 'yith_wcbm_badge[_uploaded_image_width]',
					'label'           => __( 'Width (px)', 'yith-woocommerce-badges-management' ),
					'type'            => 'number',
					'extra_row_class' => 'yith-wcbm-visible-if-image--upload',
					'std'             => 100,
					'desc'            => __( 'Set the badge width.', 'yith-woocommerce-badges-management' ),
				),
				'padding'                  => array(
					'name'            => 'yith_wcbm_badge[_padding]',
					'label'           => __( 'Padding', 'yith-woocommerce-badges-management' ),
					'desc'            => __( 'Set the badge content spacing.', 'yith-woocommerce-badges-management' ),
					'type'            => 'dimensions',
					'extra_row_class' => 'yith-wcbm-visible-if-text',
					'dimensions'      => array(
						'top'    => __( 'Top', 'yith-woocommerce-badges-management' ),
						'right'  => __( 'Right', 'yith-woocommerce-badges-management' ),
						'bottom' => __( 'Bottom', 'yith-woocommerce-badges-management' ),
						'left'   => __( 'Left', 'yith-woocommerce-badges-management' ),
					),
					'units'           => array(
						'px'         => 'px',
						'percentage' => '%',
					),
					'min'             => 0,
				),
				'border_radius'            => array(
					'name'            => 'yith_wcbm_badge[_border_radius]',
					'label'           => __( 'Border radius', 'yith-woocommerce-badges-management' ),
					'desc'            => __( 'Set the badge border radius.', 'yith-woocommerce-badges-management' ),
					'type'            => 'dimensions',
					'extra_row_class' => 'yith-wcbm-visible-if-text',
					'dimensions'      => array(
						'top-left'     => __( 'Top left', 'yith-woocommerce-badges-management' ),
						'top-right'    => __( 'Top right', 'yith-woocommerce-badges-management' ),
						'bottom-right' => __( 'Bottom right', 'yith-woocommerce-badges-management' ),
						'bottom-left'  => __( 'Bottom left', 'yith-woocommerce-badges-management' ),
					),
					'units'           => array(
						'px'         => 'px',
						'percentage' => '%',
					),
					'min'             => 0,
				),
				'opacity'                  => array(
					'name'            => 'yith_wcbm_badge[_opacity]',
					'label'           => __( 'Opacity (%)', 'yith-woocommerce-badges-management' ),
					'desc'            => __( 'Set the badge opacity. 0 is transparent, 100 is solid color.', 'yith-woocommerce-badges-management' ),
					'type'            => 'slider',
					'extra_row_class' => 'yith-wcbm-visible-if-text yith-wcbm-visible-if-image yith-wcbm-visible-if-css yith-wcbm-visible-if-advanced',
					'std'             => 100,
				),
				'rotation'                 => array(
					'name'            => 'yith_wcbm_badge[_rotation]',
					'label'           => __( 'Rotation', 'yith-woocommerce-badges-management' ),
					'desc'            => __( 'Use these values to rotate the badge.', 'yith-woocommerce-badges-management' ),
					'extra_row_class' => 'yith-wcbm-visible-if-text yith-wcbm-visible-if-image yith-wcbm-visible-if-css yith-wcbm-visible-if-advanced',
					'type'            => 'inline-fields',
					'fields'          => array(
						'x'       => array(
							'id'    => 'yith-wcbm-rotation-slider-x',
							'label' => 'X',
							'type'  => 'slider',
							'class' => 'yith-wcbm-rotation-slider',
							'max'   => 360,
						),
						'x-input' => array(
							'type'  => 'number',
							'class' => 'yith-wcbm-rotation-input',
							'data'  => array( 'linked-to' => '_rotation_x' ),
							'max'   => 360,
							'std'   => 0,
						),
						'y'       => array(
							'id'    => 'yith-wcbm-rotation-slider-y',
							'label' => 'Y',
							'type'  => 'slider',
							'class' => 'yith-wcbm-rotation-slider',
							'max'   => 360,
						),
						'y-input' => array(
							'type'  => 'number',
							'class' => 'yith-wcbm-rotation-input',
							'data'  => array( 'linked-to' => '_rotation_y' ),
							'max'   => 360,
							'std'   => 0,
						),
						'z'       => array(
							'id'    => 'yith-wcbm-rotation-slider-z',
							'label' => 'Z',
							'type'  => 'slider',
							'class' => 'yith-wcbm-rotation-slider',
							'max'   => 360,
						),
						'z-input' => array(
							'type'  => 'number',
							'class' => 'yith-wcbm-rotation-input',
							'data'  => array( 'linked-to' => '_rotation_z' ),
							'max'   => 360,
							'std'   => 0,
						),
						/**
						 * 'reset'   => array(
						 * 'type'  => 'html',
						 * 'name'  => '',
						 * 'class' => 'yith-wcbm-rotation-input--reset-container',
						 * 'html'  => '<i class="yith-icon yith-icon-reset yith-plugin-fw__tips yith-wcbm-rotation-input--reset" data-tip="' . esc_html_x( 'Reset', '[ADMIN] Badge reset rotation values in editing metabox', 'yith-woocommerce-badges-management' ) . '"></i>',
						 * ),
						 */
					),
					'min'             => 0,
					'max'             => 360,
				),
				'use_flip_text'            => array(
					'name'            => 'yith_wcbm_badge[_use_flip_text]',
					'label'           => __( 'Flip/Mirror text', 'yith-woocommerce-badges-management' ),
					'desc'            => __( 'Enable a mirror effect on the text.<br>You can flip it both horizontally and vertically.', 'yith-woocommerce-badges-management' ),
					'type'            => 'onoff',
					'extra_row_class' => 'yith-wcbm-visible-if-text yith-wcbm-visible-if-css yith-wcbm-visible-if-advanced',
				),
				'flip_text'                => array(
					'name'            => 'yith_wcbm_badge[_flip_text]',
					'label'           => __( 'Flip orientation', 'yith-woocommerce-badges-management' ),
					'desc'            => __( 'Choose the text flipping orientation to apply.', 'yith-woocommerce-badges-management' ),
					'type'            => 'radio',
					'extra_row_class' => 'yith-wcbm-visible-if-text yith-wcbm-visible-if-css yith-wcbm-visible-if-advanced yith-wcbm-flip-text-row',
					'class'           => 'yith-wcbm-radio-pill-style',
					'options'         => array(
						'vertical'   => __( 'Vertical', 'yith-woocommerce-badges-management' ),
						'horizontal' => __( 'Horizontal', 'yith-woocommerce-badges-management' ),
						'both'       => __( 'Both', 'yith-woocommerce-badges-management' ),
					),
					'std'             => 'vertical',
				),
				'position_type'            => array(
					'name'            => 'yith_wcbm_badge[_position_type]',
					'label'           => __( 'Set position', 'yith-woocommerce-badges-management' ),
					'type'            => 'radio',
					'desc'            => __( 'Choose to set the badge position using px or % or to choose a fixed position.', 'yith-woocommerce-badges-management' ),
					'extra_row_class' => 'yith-wcbm-visible-if-text yith-wcbm-visible-if-image yith-wcbm-visible-if-css yith-wcbm-visible-if-advanced',
					'class'           => 'yith-wcbm-radio-pill-style',
					'options'         => array(
						'values' => __( 'In px or %', 'yith-woocommerce-badges-management' ),
						'fixed'  => __( 'Fixed', 'yith-woocommerce-badges-management' ),
					),
					'std'             => 'values',
				),
				'anchor_point'             => array(
					'name'            => 'yith_wcbm_badge[_anchor_point]',
					'label'           => __( 'Anchor Point', 'yith-woocommerce-badges-management' ),
					'desc'            => __( 'Set the badge anchor point.', 'yith-woocommerce-badges-management' ),
					'type'            => 'radio',
					'extra_row_class' => 'yith-wcbm-visible-if-text yith-wcbm-visible-if-image yith-wcbm-visible-if-css yith-wcbm-visible-if-advanced yith-wcbm-preview-boxed-radio yith-wcbm-anchor-point-row',
					'class'           => 'yith-wcbm-anchor-point-field',
					'options'         => array(
						'top-left'     => '<span class="yith-wcbm-radio-preview-box"></span>' . __( 'Top left', 'yith-woocommerce-badges-management' ),
						'top-right'    => '<span class="yith-wcbm-radio-preview-box"></span>' . __( 'Top right', 'yith-woocommerce-badges-management' ),
						'bottom-right' => '<span class="yith-wcbm-radio-preview-box"></span>' . __( 'Bottom right', 'yith-woocommerce-badges-management' ),
						'bottom-left'  => '<span class="yith-wcbm-radio-preview-box"></span>' . __( 'Bottom left', 'yith-woocommerce-badges-management' ),
					),
					'std'             => 'top-left',
				),
				'position_values'          => array(
					'name'            => 'yith_wcbm_badge[_position_values]',
					'label'           => __( 'Position', 'yith-woocommerce-badges-management' ),
					'desc'            => __( 'Set the badge position above the product image.', 'yith-woocommerce-badges-management' ),
					'type'            => 'dimensions',
					'extra_row_class' => 'yith-wcbm-visible-if-text yith-wcbm-visible-if-image yith-wcbm-visible-if-css yith-wcbm-visible-if-advanced yith-wcbm-position-values-row',
					'allow_linked'    => false,
					'dimensions'      => array(
						'top'    => array(
							'label'             => __( 'Top', 'yith-woocommerce-badges-management' ),
							'custom_attributes' => array( 'step' => '0.01' ),
						),
						'bottom' => array(
							'label'             => __( 'Bottom', 'yith-woocommerce-badges-management' ),
							'custom_attributes' => array( 'step' => '0.01' ),
						),
						'right'  => array(
							'label'             => __( 'Right', 'yith-woocommerce-badges-management' ),
							'custom_attributes' => array( 'step' => '0.01' ),
						),
						'left'   => array(
							'label'             => __( 'Left', 'yith-woocommerce-badges-management' ),
							'custom_attributes' => array( 'step' => '0.01' ),
						),
					),
					'min'             => -50,
					'units'           => array(
						'px'         => 'px',
						'percentage' => '%',
					),
					'step'            => 0.01,
				),
				'position'                 => array(
					'name'            => 'yith_wcbm_badge[_position]',
					'label'           => __( 'Position', 'yith-woocommerce-badges-management' ),
					'type'            => 'radio',
					'extra_row_class' => 'yith-wcbm-visible-if-image yith-wcbm-visible-if-text yith-wcbm-visible-if-css yith-wcbm-visible-if-advanced yith-wcbm-preview-boxed-radio yith-wcbm-position-fixed-row',
					'class'           => 'yith-wcbm-position-field',
					'options'         => array(
						'top'    => '<span class="yith-wcbm-radio-preview-box yith-wcbm-position-preview"></span>' . __( 'Top', 'yith-woocommerce-badges-management' ),
						'middle' => '<span class="yith-wcbm-radio-preview-box yith-wcbm-position-preview"></span>' . __( 'Middle', 'yith-woocommerce-badges-management' ),
						'bottom' => '<span class="yith-wcbm-radio-preview-box yith-wcbm-position-preview"></span>' . __( 'Bottom', 'yith-woocommerce-badges-management' ),
					),
					'std'             => 'top',
				),
				'alignment'                => array(
					'name'            => 'yith_wcbm_badge[_alignment]',
					'label'           => __( 'Alignment', 'yith-woocommerce-badges-management' ),
					'type'            => 'radio',
					'extra_row_class' => 'yith-wcbm-visible-if-text yith-wcbm-visible-if-image yith-wcbm-visible-if-css yith-wcbm-visible-if-advanced yith-wcbm-preview-boxed-radio yith-wcbm-alignment-fixed-row',
					'class'           => 'yith-wcbm-alignment-field',
					'options'         => array(
						'left'   => '<span class="yith-wcbm-radio-preview-box yith-wcbm-alignment-preview"></span>' . __( 'Left', 'yith-woocommerce-badges-management' ),
						'center' => '<span class="yith-wcbm-radio-preview-box yith-wcbm-alignment-preview"></span>' . __( 'Center', 'yith-woocommerce-badges-management' ),
						'right'  => '<span class="yith-wcbm-radio-preview-box yith-wcbm-alignment-preview"></span>' . __( 'Right', 'yith-woocommerce-badges-management' ),
					),
					'std'             => 'left',
				),
				'margin'                   => array(
					'name'            => 'yith_wcbm_badge[_margin]',
					'label'           => __( 'Margin', 'yith-woocommerce-badges-management' ),
					'desc'            => __( 'Set the badge margin.', 'yith-woocommerce-badges-management' ),
					'type'            => 'dimensions',
					'extra_row_class' => 'yith-wcbm-visible-if-text yith-wcbm-visible-if-image yith-wcbm-visible-if-css yith-wcbm-visible-if-advanced',
					'dimensions'      => array(
						'top'    => __( 'Top', 'yith-woocommerce-badges-management' ),
						'bottom' => __( 'Bottom', 'yith-woocommerce-badges-management' ),
						'right'  => __( 'Right', 'yith-woocommerce-badges-management' ),
						'left'   => __( 'Left', 'yith-woocommerce-badges-management' ),
					),
					'units'           => array(
						'px'         => 'px',
						'percentage' => '%',
					),
				),
				'scale_on_mobile'          => array(
					'name'            => 'yith_wcbm_badge[_scale_on_mobile]',
					'label'           => __( 'Scale on mobile', 'yith-woocommerce-badges-management' ),
					'desc'            => __( 'Set the badge scale on mobile view.', 'yith-woocommerce-badges-management' ),
					'type'            => 'number',
					'extra_row_class' => 'yith-wcbm-visible-if-text yith-wcbm-visible-if-image yith-wcbm-visible-if-css yith-wcbm-visible-if-advanced',
					'min'             => 0,
					'std'             => 1,
					'step'            => 0.01,
				),
			),
		),
		'preview'       => array(
			'label'  => '',
			'fields' => array(
				'preview' => array(
					'label'  => '',
					'type'   => 'custom',
					'action' => 'yith_wcbm_print_badge_preview',
				),
			),
		),
	),
);
