<?php
// THIS FILE IS AUTOGENERATED, PLEASE DON'T EDIT IT DIRECTLY

return array(
	"Invoice" => array(
		__( "Invoice", 'yith-woocommerce-pdf-invoice' ),
	),
	"Tax" => array(
		__( "Tax", 'yith-woocommerce-pdf-invoice' ),
	),
	"Credit note" => array(
		__( "Credit note", 'yith-woocommerce-pdf-invoice' ),
	),
	"Order number" => array(
		__( "Order number", 'yith-woocommerce-pdf-invoice' ),
	),
	"Product SKU" => array(
		__( "Product SKU", 'yith-woocommerce-pdf-invoice' ),
	),
	"Quantity" => array(
		__( "Quantity", 'yith-woocommerce-pdf-invoice' ),
	),
	"Regular price" => array(
		__( "Regular price", 'yith-woocommerce-pdf-invoice' ),
	),
	"Product name" => array(
		__( "Product name", 'yith-woocommerce-pdf-invoice' ),
	),
	"Sale price" => array(
		__( "Sale price", 'yith-woocommerce-pdf-invoice' ),
	),
	"Background color" => array(
		__( "Background color", 'yith-woocommerce-pdf-invoice' ),
	),
	"Description" => array(
		__( "Description", 'yith-woocommerce-pdf-invoice' ),
	),
	"Total" => array(
		__( "Total", 'yith-woocommerce-pdf-invoice' ),
	),
	"Subtotal" => array(
		__( "Subtotal", 'yith-woocommerce-pdf-invoice' ),
	),
	"Tax total" => array(
		__( "Tax total", 'yith-woocommerce-pdf-invoice' ),
	),
	"Shipping" => array(
		__( "Shipping", 'yith-woocommerce-pdf-invoice' ),
	),
	"Refunded amount" => array(
		__( "Refunded amount", 'yith-woocommerce-pdf-invoice' ),
	),
	"Price" => array(
		__( "Price", 'yith-woocommerce-pdf-invoice' ),
	),
	"Discount percentage" => array(
		__( "Discount percentage", 'yith-woocommerce-pdf-invoice' ),
	),
	"Discount" => array(
		__( "Discount", 'yith-woocommerce-pdf-invoice' ),
	),
	"Dimensions" => array(
		__( "Dimensions", 'yith-woocommerce-pdf-invoice' ),
	),
	"Margin" => array(
		__( "Margin", 'yith-woocommerce-pdf-invoice' ),
	),
	"Padding" => array(
		__( "Padding", 'yith-woocommerce-pdf-invoice' ),
	),
	"Dotted" => array(
		__( "Dotted", 'yith-woocommerce-pdf-invoice' ),
	),
	"Dashed" => array(
		__( "Dashed", 'yith-woocommerce-pdf-invoice' ),
	),
	"Height" => array(
		__( "Height", 'yith-woocommerce-pdf-invoice' ),
	),
	"Customer info" => array(
		__( "Customer info", 'yith-woocommerce-pdf-invoice' ),
	),
	"Add the information about the customer who requested the order. Placeholders available:" => array(
		__( "Add the information about the customer who requested the order. Placeholders available:", 'yith-woocommerce-pdf-invoice' ),
	),
	"Order Date type" => array(
		__( "Order Date type", 'yith-woocommerce-pdf-invoice' ),
	),
	"Date" => array(
		__( "Date", 'yith-woocommerce-pdf-invoice' ),
	),
	"Add the information about the date inside the document." => array(
		__( "Add the information about the date inside the document.", 'yith-woocommerce-pdf-invoice' ),
	),
	"Document number" => array(
		__( "Document number", 'yith-woocommerce-pdf-invoice' ),
	),
	"Add the number of the document. Use the placeholder {{document_number}} to show the number of the document." => array(
		__( "Add the number of the document. Use the placeholder {{document_number}} to show the number of the document.", 'yith-woocommerce-pdf-invoice' ),
	),
	"Product Table settings" => array(
		__( "Product Table settings", 'yith-woocommerce-pdf-invoice' ),
	),
	"Add the number of the order. Use the placeholder {{order_number}} to show the order number." => array(
		__( "Add the number of the order. Use the placeholder {{order_number}} to show the order number.", 'yith-woocommerce-pdf-invoice' ),
	),
	"Product thumbnail" => array(
		__( "Product thumbnail", 'yith-woocommerce-pdf-invoice' ),
	),
	"Weight" => array(
		__( "Weight", 'yith-woocommerce-pdf-invoice' ),
	),
	"Refund description" => array(
		__( "Refund description", 'yith-woocommerce-pdf-invoice' ),
	),
	"Show percentage tax" => array(
		__( "Show percentage tax", 'yith-woocommerce-pdf-invoice' ),
	),
	"Total with taxes" => array(
		__( "Total with taxes", 'yith-woocommerce-pdf-invoice' ),
	),
	"Fees" => array(
		__( "Fees", 'yith-woocommerce-pdf-invoice' ),
	),
	"Titles" => array(
		__( "Titles", 'yith-woocommerce-pdf-invoice' ),
	),
	"Color" => array(
		__( "Color", 'yith-woocommerce-pdf-invoice' ),
	),
	"Border color" => array(
		__( "Border color", 'yith-woocommerce-pdf-invoice' ),
	),
	"Items" => array(
		__( "Items", 'yith-woocommerce-pdf-invoice' ),
	),
	"Product Table" => array(
		__( "Product Table", 'yith-woocommerce-pdf-invoice' ),
	),
	"Add the product table inside the template." => array(
		__( "Add the product table inside the template.", 'yith-woocommerce-pdf-invoice' ),
	),
	"Order discount in the invoice summary amounts" => array(
		__( "Order discount in the invoice summary amounts", 'yith-woocommerce-pdf-invoice' ),
	),
	"Order subtotal inclusive of order discount" => array(
		__( "Order subtotal inclusive of order discount", 'yith-woocommerce-pdf-invoice' ),
	),
	"Broken down taxes in the invoice summary" => array(
		__( "Broken down taxes in the invoice summary", 'yith-woocommerce-pdf-invoice' ),
	),
	"Table settings" => array(
		__( "Table settings", 'yith-woocommerce-pdf-invoice' ),
	),
	"Subtotal labels" => array(
		__( "Subtotal labels", 'yith-woocommerce-pdf-invoice' ),
	),
	"Total settings" => array(
		__( "Total settings", 'yith-woocommerce-pdf-invoice' ),
	),
	"Total Table" => array(
		__( "Total Table", 'yith-woocommerce-pdf-invoice' ),
	),
	"Add the total table inside the template." => array(
		__( "Add the total table inside the template.", 'yith-woocommerce-pdf-invoice' ),
	),
	"Shipping info" => array(
		__( "Shipping info", 'yith-woocommerce-pdf-invoice' ),
	),
	"Add the information about the shipping order. Placeholders available:" => array(
		__( "Add the information about the shipping order. Placeholders available:", 'yith-woocommerce-pdf-invoice' ),
	),
	"SKU:" => array(
		__( "SKU:", 'yith-woocommerce-pdf-invoice' ),
	),
	"Weight:" => array(
		__( "Weight:", 'yith-woocommerce-pdf-invoice' ),
	),
	"Dimensions:" => array(
		__( "Dimensions:", 'yith-woocommerce-pdf-invoice' ),
	),
	"Enter your licence key" => array(
		__( "Enter your licence key", 'yith-woocommerce-pdf-invoice' ),
	),
	"to unlock 8 PDF templates with different designs and styles" => array(
		__( "to unlock 8 PDF templates with different designs and styles", 'yith-woocommerce-pdf-invoice' ),
	),
	"Builder pdf template: description optionChoose the date information to display." => array(
		_x( "Choose the date information to display.", "Builder pdf template: description option", 'yith-woocommerce-pdf-invoice' ),
	),
	"Builder pdf template: optionOrder creation date" => array(
		_x( "Order creation date", "Builder pdf template: option", 'yith-woocommerce-pdf-invoice' ),
	),
	"Builder pdf template: optionOrder completed date" => array(
		_x( "Order completed date", "Builder pdf template: option", 'yith-woocommerce-pdf-invoice' ),
	),
	"Builder pdf template: optionInvoice creation date" => array(
		_x( "Invoice creation date", "Builder pdf template: option", 'yith-woocommerce-pdf-invoice' ),
	),
	"Builder pdf template: optionCurrent date" => array(
		_x( "Current date", "Builder pdf template: option", 'yith-woocommerce-pdf-invoice' ),
	),
	"PDF template builder product table label for the option to select the document typeDocument type" => array(
		_x( "Document type", "PDF template builder product table label for the option to select the document type", 'yith-woocommerce-pdf-invoice' ),
	),
	"PDF template block titleOrder amount" => array(
		_x( "Order amount", "PDF template block title", 'yith-woocommerce-pdf-invoice' ),
	),
	"PDF template block order amount block descriptionAdd the amount of the order. Use the placeholder {{order_amount}} to show the order amount or {{refunded_amount}} for credit notes." => array(
		_x( "Add the amount of the order. Use the placeholder {{order_amount}} to show the order amount or {{refunded_amount}} for credit notes.", "PDF template block order amount block description", 'yith-woocommerce-pdf-invoice' ),
	),
	"PDF template builder product table label for the option to show or hide columnsShow/Hide table columns" => array(
		_x( "Show/Hide table columns", "PDF template builder product table label for the option to show or hide columns", 'yith-woocommerce-pdf-invoice' ),
	),
	"PDF template builder product table label for the option to show or hide additional itemsShow/Hide additional items" => array(
		_x( "Show/Hide additional items", "PDF template builder product table label for the option to show or hide additional items", 'yith-woocommerce-pdf-invoice' ),
	),
	"subtotal labelSubtotal" => array(
		_x( "Subtotal", "subtotal label", 'yith-woocommerce-pdf-invoice' ),
	),
	"Label for subtotal which include the discountDiscount" => array(
		_x( "Discount", "Label for subtotal which include the discount", 'yith-woocommerce-pdf-invoice' ),
	),
	" subtotal with included discountinc" => array(
		_x( "inc", " subtotal with included discount", 'yith-woocommerce-pdf-invoice' ),
	),
	"subtotal with excluded discountexc" => array(
		_x( "exc", "subtotal with excluded discount", 'yith-woocommerce-pdf-invoice' ),
	),
	"Builder pdf template - Label background optionBackground image" => array(
		_x( "Background image", "Builder pdf template - Label background option", 'yith-woocommerce-pdf-invoice' ),
	),
	"Label to upload a background image for the pdf documentUpload" => array(
		_x( "Upload", "Label to upload a background image for the pdf document", 'yith-woocommerce-pdf-invoice' ),
	),
	"Label to reset the background image for the pdf documentReset" => array(
		_x( "Reset", "Label to reset the background image for the pdf document", 'yith-woocommerce-pdf-invoice' ),
	),
	"Builder pdf template - Label Footer optionFooter" => array(
		_x( "Footer", "Builder pdf template - Label Footer option", 'yith-woocommerce-pdf-invoice' ),
	),
	"Builder pdf template - Description Footer optionUse {PAGENO} to show the number of the page." => array(
		_x( "Use {PAGENO} to show the number of the page.", "Builder pdf template - Description Footer option", 'yith-woocommerce-pdf-invoice' ),
	),
);