module.exports = {
  All: [
    { id: 'porto-icon-spin1', title: 'Spin1' },
    { id: 'porto-icon-spin2', title: 'Spin2' },
    { id: 'porto-icon-spin3', title: 'Spin3' },
    { id: 'porto-icon-spin4', title: 'Spin4' },
    { id: 'porto-icon-spin5', title: 'Spin5' },
    { id: 'porto-icon-spin6', title: 'Spin6' },
    { id: 'porto-icon-firefox', title: 'Firefox' },
    { id: 'porto-icon-chrome', title: 'Chrome' },
    { id: 'porto-icon-opera', title: 'Opera' },
    { id: 'porto-icon-ie', title: 'Ie' },
    { id: 'porto-icon-phone', title: 'Phone' },
    { id: 'porto-icon-down-dir', title: 'Down Dir' },
    { id: 'porto-icon-cart', title: 'Cart' },
    { id: 'porto-icon-up-dir', title: 'Up Dir' },
    { id: 'porto-icon-mode-grid', title: 'Mode Grid' },
    { id: 'porto-icon-mode-list', title: 'Mode List' },
    { id: 'porto-icon-compare', title: 'Compare' },
    { id: 'porto-icon-wishlist', title: 'Wishlist' },
    { id: 'porto-icon-search', title: 'Search' },
    { id: 'porto-icon-left-dir', title: 'Left Dir' },
    { id: 'porto-icon-right-dir', title: 'Right Dir' },
    { id: 'porto-icon-down-open', title: 'Down Open' },
    { id: 'porto-icon-left-open', title: 'Left Open' },
    { id: 'porto-icon-right-open', title: 'Right Open' },
    { id: 'porto-icon-up-open', title: 'Up Open' },
    { id: 'porto-icon-angle-left', title: 'Angle Left' },
    { id: 'porto-icon-angle-right', title: 'Angle Right' },
    { id: 'porto-icon-angle-up', title: 'Angle Up' },
    { id: 'porto-icon-angle-down', title: 'Angle Down' },
    { id: 'porto-icon-down', title: 'Down' },
    { id: 'porto-icon-left', title: 'Left' },
    { id: 'porto-icon-right', title: 'Right' },
    { id: 'porto-icon-up', title: 'Up' },
    { id: 'porto-icon-angle-double-left', title: 'Angle Double Left' },
    { id: 'porto-icon-angle-double-right', title: 'Angle Double Right' },
    { id: 'porto-icon-angle-double-up', title: 'Angle Double Up' },
    { id: 'porto-icon-angle-double-down', title: 'Angle Double Down' },
    { id: 'porto-icon-mail', title: 'Mail' },
    { id: 'porto-icon-location', title: 'Location' },
    { id: 'porto-icon-skype', title: 'Skype' },
    { id: 'porto-icon-right-open-big', title: 'Right Open Big' },
    { id: 'porto-icon-left-open-big', title: 'Left Open Big' },
    { id: 'porto-icon-down-open-big', title: 'Down Open Big' },
    { id: 'porto-icon-up-open-big', title: 'Up Open Big' },
    { id: 'porto-icon-cancel', title: 'Cancel' },
    { id: 'porto-icon-user', title: 'User' },
    { id: 'porto-icon-mail-alt', title: 'Mail Alt' },
    { id: 'porto-icon-fax', title: 'Fax' },
    { id: 'porto-icon-lock', title: 'Lock' },
    { id: 'porto-icon-company', title: 'Company' },
    { id: 'porto-icon-city', title: 'City' },
    { id: 'porto-icon-post', title: 'Post' },
    { id: 'porto-icon-country', title: 'Country' },
    { id: 'porto-icon-calendar', title: 'Calendar' },
    { id: 'porto-icon-doc', title: 'Doc' },
    { id: 'porto-icon-mobile', title: 'Mobile' },
    { id: 'porto-icon-clock', title: 'Clock' },
    { id: 'porto-icon-chat', title: 'Chat' },
    { id: 'porto-icon-tag', title: 'Tag' },
    { id: 'porto-icon-folder', title: 'Folder' },
    { id: 'porto-icon-folder-open', title: 'Folder Open' },
    { id: 'porto-icon-forward', title: 'Forward' },
    { id: 'porto-icon-reply', title: 'Reply' },
    { id: 'porto-icon-cog', title: 'Cog' },
    { id: 'porto-icon-cog-alt', title: 'Cog Alt' },
    { id: 'porto-icon-wrench', title: 'Wrench' },
    { id: 'porto-icon-quote-left', title: 'Quote Left' },
    { id: 'porto-icon-quote-right', title: 'Quote Right' },
    { id: 'porto-icon-gift', title: 'Gift' },
    { id: 'porto-icon-dollar', title: 'Dollar' },
    { id: 'porto-icon-euro', title: 'Euro' },
    { id: 'porto-icon-pound', title: 'Pound' },
    { id: 'porto-icon-rupee', title: 'Rupee' },
    { id: 'porto-icon-yen', title: 'Yen' },
    { id: 'porto-icon-rouble', title: 'Rouble' },
    { id: 'porto-icon-try', title: 'Try' },
    { id: 'porto-icon-won', title: 'Won' },
    { id: 'porto-icon-bitcoin', title: 'Bitcoin' },
    { id: 'porto-icon-ok', title: 'Ok' },
    { id: 'porto-icon-chevron-left', title: 'Chevron Left' },
    { id: 'porto-icon-chevron-right', title: 'Chevron Right' },
    { id: 'porto-icon-export', title: 'Export' },
    { id: 'porto-icon-star', title: 'Star' },
    { id: 'porto-icon-star-empty', title: 'Star Empty' },
    { id: 'porto-icon-plus-squared', title: 'Plus Squared' },
    { id: 'porto-icon-minus-squared', title: 'Minus Squared' },
    { id: 'porto-icon-plus-squared-alt', title: 'Plus Squared Alt' },
    { id: 'porto-icon-minus-squared-alt', title: 'Minus Squared Alt' },
    { id: 'porto-icon-truck', title: 'Truck' },
    { id: 'porto-icon-lifebuoy', title: 'Lifebuoy' },
    { id: 'porto-icon-pencil', title: 'Pencil' },
    { id: 'porto-icon-users', title: 'Users' },
    { id: 'porto-icon-video', title: 'Video' },
    { id: 'porto-icon-menu', title: 'Menu' },
    { id: 'porto-icon-desktop', title: 'Desktop' },
    { id: 'porto-icon-doc-inv', title: 'Doc Inv' },
    { id: 'porto-icon-circle', title: 'Circle' },
    { id: 'porto-icon-circle-empty', title: 'Circle Empty' },
    { id: 'porto-icon-circle-thin', title: 'Circle Thin' },
    { id: 'porto-icon-mini-cart', title: 'Mini Cart' },
    { id: 'porto-icon-paper-plane', title: 'Paper Plane' },
    { id: 'porto-icon-attention-alt', title: 'Attention Alt' },
    { id: 'porto-icon-info', title: 'Info' },
    { id: 'porto-icon-compare-link', title: 'Compare Link' },
    { id: 'porto-icon-cat-default', title: 'Cat Default' },
    { id: 'porto-icon-cat-computer', title: 'Cat Computer' },
    { id: 'porto-icon-cat-couch', title: 'Cat Couch' },
    { id: 'porto-icon-cat-garden', title: 'Cat Garden' },
    { id: 'porto-icon-cat-gift', title: 'Cat Gift' },
    { id: 'porto-icon-cat-shirt', title: 'Cat Shirt' },
    { id: 'porto-icon-cat-sport', title: 'Cat Sport' },
    { id: 'porto-icon-cat-toys', title: 'Cat Toys' },
    { id: 'porto-icon-tag-line', title: 'Tag L`ine' },
    { id: 'porto-icon-bag', title: 'Bag' },
    { id: 'porto-icon-search-1', title: 'Search-1' },
    { id: 'porto-icon-plus', title: 'Plus' },
    { id: 'porto-icon-minus', title: 'Minus' },
    { id: 'porto-icon-search-2', title: 'Search-2' },
    { id: 'porto-icon-bag-1', title: 'Bag-1' },
    { id: 'porto-icon-online-support', title: 'Online Support' },
    { id: 'porto-icon-shopping-bag', title: 'Shopping Bag' },
    { id: 'porto-icon-us-dollar', title: 'Us Dollar' },
    { id: 'porto-icon-shipped', title: 'Shipped' },
    { id: 'porto-icon-list', title: 'List' },
    { id: 'porto-icon-money', title: 'Money' },
    { id: 'porto-icon-shipping', title: 'Shipping' },
    { id: 'porto-icon-support', title: 'Support' },
    { id: 'porto-icon-bag-2', title: 'Bag-2' },
    { id: 'porto-icon-grid', title: 'Grid' },
    { id: 'porto-icon-bag-3', title: 'Bag-3' },
    { id: 'porto-icon-direction', title: 'Direction' },
    { id: 'porto-icon-home', title: 'Home' },
    { id: 'porto-icon-magnifier', title: 'Magnifier' },
    { id: 'porto-icon-magnifier-add', title: 'Magnifier Add' },
    { id: 'porto-icon-magnifier-remove', title: 'Magnifier Remove' },
    { id: 'porto-icon-phone-1', title: 'Phone-1' },
    { id: 'porto-icon-clock-1', title: 'Clock-1' },
    { id: 'porto-icon-heart', title: 'Heart' },
    { id: 'porto-icon-heart-1', title: 'Heart-1' },
    { id: 'porto-icon-earphones-alt', title: 'Earphones Alt' },
    { id: 'porto-icon-credit-card', title: 'Credit Card' },
    { id: 'porto-icon-action-undo', title: 'Action Undo' },
    { id: 'porto-icon-envolope', title: 'Envolope' },
    { id: 'porto-icon-twitter', title: 'Twitter' },
    { id: 'porto-icon-facebook', title: 'Facebook' },
    { id: 'porto-icon-spinner', title: 'Spinner' },
    { id: 'porto-icon-instagram', title: 'Instagram' },
    { id: 'porto-icon-check-empty', title: 'Check Empty' },
    { id: 'porto-icon-check', title: 'Check' },
    { id: 'porto-icon-category-gifts', title: 'Ribbon, Category Gifts' },
    { id: 'porto-icon-category-home', title: 'Home, Category' },
    { id: 'porto-icon-category-motors', title: 'Car, Motors' },
    { id: 'porto-icon-category-music', title: 'Music(microphone, sound)' },
    { id: 'porto-icon-category-electronics', title: 'Electronics(clock)' },
    { id: 'porto-icon-category-fashion', title: 'Fashion(clothes, women, dress)' },
    { id: 'porto-icon-category-furniture', title: 'Furniture(chair)' },
    { id: 'porto-icon-category-garden', title: 'Garden(flower)' },
    { id: 'porto-icon-category-lanterns-lighting', title: 'Lanterns lighting' },
    { id: 'porto-icon-category-mechanics', title: 'Mechanics' },
    { id: 'porto-icon-category-motorcycles', title: 'Motorcycle(vehicle, bike)' },
    { id: 'porto-icon-category-sound-video', title: 'Sound Video(volume)' },
    { id: 'porto-icon-category-steering', title: 'Steering' },
    { id: 'porto-icon-category-external-accessories', title: 'External Accessories(truck, car)' },
    { id: 'porto-icon-category-fluids', title: 'Fluids' },
    { id: 'porto-icon-category-hot-deals', title: 'Hot Deals(tagline)' },
    { id: 'porto-icon-category-internal-accessories', title: 'Internal Accessories' },
    { id: 'porto-icon-category-chains', title: 'Bicycle Chains' },
    { id: 'porto-icon-category-frames', title: 'Bicycle Frames' },
    { id: 'porto-icon-category-pedals', title: 'Bicycle Pedals' },
    { id: 'porto-icon-category-saddle', title: 'Bicycle Saddle' },
    { id: 'porto-icon-category-tools', title: 'Spanner Wrench' },
    { id: 'porto-icon-search-3', title: 'Search' },
    { id: 'porto-icon-secure-payment', title: 'Secure Payment(card, lock)' },
    { id: 'porto-icon-user-2', title: 'User' },
    { id: 'porto-icon-wishlist-2', title: 'Wishlist' },
    { id: 'porto-icon-gift-2', title: 'Gift' },
    { id: 'porto-icon-edit', title: 'Edit(pencil)' },
    { id: 'porto-icon-chef', title: 'Chef' },
    { id: 'porto-icon-smiling-girl', title: 'Smiling Girl' },
    { id: 'porto-icon-tshirt', title: 'T-Shirt' },
    { id: 'porto-icon-boy-broad-smile', title: 'Boy Broad Smile' },
    { id: 'porto-icon-smiling-baby', title: 'Smiling Baby' },
    { id: 'porto-icon-bars', title: 'Bars(menu button of three lines of outline)' },
    { id: 'porto-icon-tag-percent', title: 'Tag Percent' },
    { id: 'porto-icon-joystick', title: 'Joystick(console)' },
    { id: 'porto-icon-shopping-cart', title: 'Shopping Cart(bag)' },
    { id: 'porto-icon-phone-2', title: 'Phone' },
    { id: 'porto-icon-comida-organica', title: 'Hand & Sprout' },
    { id: 'porto-icon-estrela', title: 'Shining Star' },
    { id: 'porto-icon-fazer-compras', title: 'Fazer Compras' },
    { id: 'porto-icon-gluten', title: 'Gluten(Twig, Sprig)' },
    { id: 'porto-icon-arrow-forward-right', title: 'Arrow Forward Right' },
    { id: 'porto-icon-percent-circle', title: 'Percent Circle' },
    { id: 'porto-icon-pulley', title: 'Pulley' },
    { id: 'porto-icon-password-lock', title: 'Password Lock' },
    { id: 'porto-icon-pin', title: 'Pin, Location' },
    { id: 'porto-icon-rotulo', title: 'Routulo, New Label' },
    { id: 'porto-icon-cart-thick', title: 'Shopping Cart Thick(bag)' },
    { id: 'porto-icon-check-circle', title: 'Check, Circle' },
    { id: 'porto-icon-envelope', title: 'Envelope, E-Mail' },
    { id: 'porto-icon-business-book', title: 'Book' },
    { id: 'porto-icon-long-arrow-right', title: 'Long Arrow Right' },
    { id: 'porto-icon-percent-shape', title: 'Percent, Finance' },
    { id: 'porto-icon-sale-label', title: 'Sale Label' },
    { id: 'porto-icon-help-circle', title: 'Help, Circle, Question' },
    { id: 'porto-icon-sale-discount', title: 'Sale, Discount' },
    { id: 'porto-icon-shipping-truck', title: 'Shipping Truck' },
    { id: 'porto-icon-user-3', title: 'User (Person, Man)' },
    { id: 'porto-icon-long-arrow-alt', title: 'Long Arrow Right Alt' },
    { id: 'porto-icon-map-location', title: 'Map Location (pin)' },
    { id: 'porto-icon-phone-call', title: 'Calling Phone' },
    { id: 'porto-icon-tablet', title: 'Tablet' }
  ]
}
