<?php
// THIS FILE IS AUTOGENERATED, PLEASE DON'T EDIT IT DIRECTLY

return array(
	"The alternative content is hidden." => array(
		__( "The alternative content is hidden.", 'yith-woocommerce-membership' ),
	),
	"The alternative content is visible." => array(
		__( "The alternative content is visible.", 'yith-woocommerce-membership' ),
	),
	"Hide the alternative content" => array(
		__( "Hide the alternative content", 'yith-woocommerce-membership' ),
	),
	"Block titleMembers-only content starts here" => array(
		_x( "Members-only content starts here", "Block title", 'yith-woocommerce-membership' ),
	),
	"Block nameMembers-only content start" => array(
		_x( "Members-only content start", "Block name", 'yith-woocommerce-membership' ),
	),
);